!=======================================================================
! Generated by  : PSCAD v4.2.1
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE DSDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
      REAL    DERIV1        ! Derivative Function
      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'
      REAL    REALPOLE      ! Real Pole
      REAL    DELAY         ! Delay Line

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Parameters

! Electrical Node Indexes

! Control Signals
      REAL    RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL    RT_7, RT_8, RT_9, RT_10, RT_11
      REAL    RT_12, RT_13, RT_14, RT_15, RT_16
      REAL    RT_17, RT_18, RT_19, RT_20, RT_21
      REAL    RT_22, RT_23, RT_24, RT_25, RT_26
      REAL    RT_27, RT_28, RT_29, RT_30, RT_31
      REAL    RT_32, RT_33, RT_34, RT_35, RT_36
      REAL    RT_37, RT_38

! Internal Variables
      REAL    RVD2_1(2), RVD2_2(2)

! Indexing variables
      INTEGER ISTOF, IT_0                         ! Storage Indexes
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Record local indexes
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage
      NTXFR = NTXFR + 1
      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF

! Record Offset and Increment Storage Counters
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 38
      IPGB      = NPGB
      NPGB      = NPGB + 17
      NNODE     = NNODE + 2


!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      RT_3     = STOF(ISTOF + 3)
      RT_4     = STOF(ISTOF + 4)
      RT_5     = STOF(ISTOF + 5)
      RT_6     = STOF(ISTOF + 6)
      RT_7     = STOF(ISTOF + 7)
      RT_8     = STOF(ISTOF + 8)
      RT_9     = STOF(ISTOF + 9)
      RT_10    = STOF(ISTOF + 10)
      RT_11    = STOF(ISTOF + 11)
      RT_12    = STOF(ISTOF + 12)
      RT_13    = STOF(ISTOF + 13)
      RT_14    = STOF(ISTOF + 14)
      RT_15    = STOF(ISTOF + 15)
      RT_16    = STOF(ISTOF + 16)
      RT_17    = STOF(ISTOF + 17)
      RT_18    = STOF(ISTOF + 18)
      RT_19    = STOF(ISTOF + 19)
      RT_20    = STOF(ISTOF + 20)
      RT_21    = STOF(ISTOF + 21)
      RT_22    = STOF(ISTOF + 22)
      RT_23    = STOF(ISTOF + 23)
      RT_24    = STOF(ISTOF + 24)
      RT_25    = STOF(ISTOF + 25)
      RT_26    = STOF(ISTOF + 26)
      RT_27    = STOF(ISTOF + 27)
      RT_28    = STOF(ISTOF + 28)
      RT_29    = STOF(ISTOF + 29)
      RT_30    = STOF(ISTOF + 30)
      RT_31    = STOF(ISTOF + 31)
      RT_32    = STOF(ISTOF + 32)
      RT_33    = STOF(ISTOF + 33)
      RT_34    = STOF(ISTOF + 34)
      RT_35    = STOF(ISTOF + 35)
      RT_36    = STOF(ISTOF + 36)
      RT_37    = STOF(ISTOF + 37)
      RT_38    = STOF(ISTOF + 38)

!---------------------------------------
! Transfer from Imports
!---------------------------------------


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Read Model data (if any)
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[time-sig] Output of Simulation Time 
      RT_1 = TIME

! 20:[compare] Single Input Level Comparator 
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_1,0.0,0.0,1.0,RVD2_1)
      RT_2 = RVD2_1(1)

! 30:[gain] Gain Block 
!  Gain
      RT_3 = 3.0 * RT_2
!

! 40:[pgb] Output Channel 'Odp.skok.prop'

      PGB(IPGB+1) = RT_3

! 50:[time-sig] Output of Simulation Time 
      RT_4 = TIME

! 60:[compare] Single Input Level Comparator 
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_4,0.0,0.0,1.0,RVD2_1)
      RT_5 = RVD2_1(1)

! 70:[derivative] Derivative with a time constant 
!  Derivative
      RT_7 = DERIV1( 1.0 , RT_5 )
!

! 80:[gain] Gain Block 
!  Gain
      RT_6 = 3.0 * RT_7
!

! 90:[pgb] Output Channel 'Odp.imp.prop'

      PGB(IPGB+2) = RT_6

! 100:[time-sig] Output of Simulation Time 
      RT_8 = TIME

! 110:[compare] Single Input Level Comparator 
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_8,0.0,0.0,1.0,RVD2_1)
      RT_23 = RVD2_1(1)

! 120:[integral] Interpolated Integrator 
      RVD2_1(1) = RT_23
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
!
      RT_9 = EMTDC_XINT(0, 0, 0, 0.0, 2.73, 0.0,-100.0, 100.0,RVD2_2,RVD&
     &2_1)

! 130:[pgb] Output Channel 'odp.skok.calk.ideal'

      PGB(IPGB+3) = RT_9

! 140:[integral] Interpolated Integrator 
      RVD2_1(1) = RT_23
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
!
      RT_10 = EMTDC_XINT(0, 0, 0, 0.0, 2.73, 0.0,-100.0, 100.0,RVD2_2,RV&
     &D2_1)

! 150:[realpole] Real Pole 
!  Real_Pole
      RT_11 = REALPOLE(0,1,0,3.0,2.37,RT_10,0.0,-10.0,10.0)

! 160:[pgb] Output Channel 'odp.skok.calk.rzecz'

      PGB(IPGB+4) = RT_11

! 170:[derivative] Derivative with a time constant 
!  Derivative
      RT_12 = DERIV1( 2.73 , RT_23 )
!

! 180:[integral] Interpolated Integrator 
      RVD2_1(1) = RT_12
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
!
      RT_14 = EMTDC_XINT(0, 0, 0, 0.0, 2.73, 0.0,-100.0, 100.0,RVD2_2,RV&
     &D2_1)

! 190:[pgb] Output Channel 'odp.imp.calk.ideal'

      PGB(IPGB+5) = RT_14

! 200:[derivative] Derivative with a time constant 
!  Derivative
      RT_13 = DERIV1( 2.73 , RT_23 )
!

! 210:[integral] Interpolated Integrator 
      RVD2_1(1) = RT_13
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
!
      RT_15 = EMTDC_XINT(0, 0, 0, 0.0, 2.73, 0.0,-100.0, 100.0,RVD2_2,RV&
     &D2_1)

! 220:[realpole] Real Pole 
!  Real_Pole
      RT_16 = REALPOLE(0,1,0,3.0,2.37,RT_15,0.0,-10.0,10.0)

! 230:[pgb] Output Channel 'odp.imp.calk.rzecz'

      PGB(IPGB+6) = RT_16

! 240:[derivative] Derivative with a time constant 
!  Derivative
      RT_17 = DERIV1( 2.73 , RT_23 )
!

! 250:[pgb] Output Channel 'odp.skok.roz.ideal'

      PGB(IPGB+7) = RT_17

! 260:[derivative] Derivative with a time constant 
!  Derivative
      RT_18 = DERIV1( 2.73 , RT_23 )
!

! 270:[realpole] Real Pole 
!  Real_Pole
      RT_19 = REALPOLE(0,1,0,3.0,2.37,RT_18,0.0,-10.0,10.0)

! 280:[pgb] Output Channel 'odp.skok.roz.ideal'

      PGB(IPGB+8) = RT_19

! 290:[realpole] Real Pole 
!  Real_Pole
      RT_20 = REALPOLE(0,1,0,3.0,2.37,RT_23,0.0,-10.0,10.0)

! 300:[pgb] Output Channel 'odp.skok.inercyjnego I rzedu'

      PGB(IPGB+9) = RT_20

! 310:[realpole] Real Pole 
!  Real_Pole
      RT_21 = REALPOLE(0,1,0,1.0,2.73,RT_23,0.0,-10.0,10.0)

! 320:[realpole] Real Pole 
!  Real_Pole
      RT_22 = REALPOLE(0,1,0,3.0,2.37,RT_21,0.0,-10.0,10.0)

! 330:[pgb] Output Channel 'odp.skok.inercyjnego II rzedu'

      PGB(IPGB+10) = RT_22

! 340:[tdelay] Delay Function 
!  Delay
      RT_24 = DELAY(2.73, 100, RT_23)
!

! 350:[pgb] Output Channel 'odp.skok.opoz'

      PGB(IPGB+11) = RT_24

! 360:[time-sig] Output of Simulation Time 
      RT_27 = TIME

! 370:[compare] Single Input Level Comparator 
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_27,0.0,0.0,1.0,RVD2_1)
      RT_36 = RVD2_1(1)

! 380:[realpole] Real Pole 
!  Real_Pole
      RT_25 = REALPOLE(0,1,0,1.0,2.73,RT_36,0.0,-10.0,10.0)

! 390:[realpole] Real Pole 
!  Real_Pole
      RT_26 = REALPOLE(0,1,0,3.0,2.37,RT_25,0.0,-10.0,10.0)

! 400:[pgb] Output Channel 'k =3'

      PGB(IPGB+12) = RT_26

! 410:[realpole] Real Pole 
!  Real_Pole
      RT_28 = REALPOLE(0,1,0,1.0,2.73,RT_36,0.0,-10.0,10.0)

! 420:[realpole] Real Pole 
!  Real_Pole
      RT_29 = REALPOLE(0,1,0,6.0,2.37,RT_28,0.0,-10.0,10.0)

! 430:[pgb] Output Channel 'k =6'

      PGB(IPGB+13) = RT_29

! 440:[realpole] Real Pole 
!  Real_Pole
      RT_30 = REALPOLE(0,1,0,1.0,2.73,RT_36,0.0,-10.0,10.0)

! 450:[realpole] Real Pole 
!  Real_Pole
      RT_31 = REALPOLE(0,1,0,9.0,2.37,RT_30,0.0,-10.0,10.0)

! 460:[pgb] Output Channel 'k =9'

      PGB(IPGB+14) = RT_31

! 470:[realpole] Real Pole 
!  Real_Pole
      RT_32 = REALPOLE(0,1,0,1.0,3.0,RT_36,0.0,-10.0,10.0)

! 480:[realpole] Real Pole 
!  Real_Pole
      RT_33 = REALPOLE(0,1,0,3.0,2.37,RT_32,0.0,-10.0,10.0)

! 490:[pgb] Output Channel 'T =3'

      PGB(IPGB+15) = RT_33

! 500:[realpole] Real Pole 
!  Real_Pole
      RT_34 = REALPOLE(0,1,0,1.0,6.0,RT_36,0.0,-10.0,10.0)

! 510:[realpole] Real Pole 
!  Real_Pole
      RT_35 = REALPOLE(0,1,0,3.0,2.37,RT_34,0.0,-10.0,10.0)

! 520:[pgb] Output Channel 'T =6'

      PGB(IPGB+16) = RT_35

! 530:[realpole] Real Pole 
!  Real_Pole
      RT_37 = REALPOLE(0,1,0,1.0,9.0,RT_36,0.0,-10.0,10.0)

! 540:[realpole] Real Pole 
!  Real_Pole
      RT_38 = REALPOLE(0,1,0,3.0,2.37,RT_37,0.0,-10.0,10.0)

! 550:[pgb] Output Channel 'T =9'

      PGB(IPGB+17) = RT_38

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 3) = RT_3
      STOF(ISTOF + 4) = RT_4
      STOF(ISTOF + 5) = RT_5
      STOF(ISTOF + 6) = RT_6
      STOF(ISTOF + 7) = RT_7
      STOF(ISTOF + 8) = RT_8
      STOF(ISTOF + 9) = RT_9
      STOF(ISTOF + 10) = RT_10
      STOF(ISTOF + 11) = RT_11
      STOF(ISTOF + 12) = RT_12
      STOF(ISTOF + 13) = RT_13
      STOF(ISTOF + 14) = RT_14
      STOF(ISTOF + 15) = RT_15
      STOF(ISTOF + 16) = RT_16
      STOF(ISTOF + 17) = RT_17
      STOF(ISTOF + 18) = RT_18
      STOF(ISTOF + 19) = RT_19
      STOF(ISTOF + 20) = RT_20
      STOF(ISTOF + 21) = RT_21
      STOF(ISTOF + 22) = RT_22
      STOF(ISTOF + 23) = RT_23
      STOF(ISTOF + 24) = RT_24
      STOF(ISTOF + 25) = RT_25
      STOF(ISTOF + 26) = RT_26
      STOF(ISTOF + 27) = RT_27
      STOF(ISTOF + 28) = RT_28
      STOF(ISTOF + 29) = RT_29
      STOF(ISTOF + 30) = RT_30
      STOF(ISTOF + 31) = RT_31
      STOF(ISTOF + 32) = RT_32
      STOF(ISTOF + 33) = RT_33
      STOF(ISTOF + 34) = RT_34
      STOF(ISTOF + 35) = RT_35
      STOF(ISTOF + 36) = RT_36
      STOF(ISTOF + 37) = RT_37
      STOF(ISTOF + 38) = RT_38

!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE DSOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indexes

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ISTOL, ISTOI, ISTOF                 ! Storage Indexes
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Record local indexes
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage
      NTXFR = NTXFR + 1
      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)

! Record Offset and Increment Storage Counters
      NPGB      = NPGB + 17
      NNODE     = NNODE + 2


!---------------------------------------
! Transfers from storage arrays
!---------------------------------------


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Read Model data (if any)
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF

!---------------------------------------
! Generated code from module definition
!---------------------------------------


!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------


!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

