#line 1 "Main.f"
/* Main.f -- translated by f2c (version 19990326).
   You must link the resulting object file with the libraries:
	-lf2c -lm   (in that order)
*/

#include "f2c.h"

#line 1 "Main.f"
/* Common Block Declarations */

struct {
    integer e_ndim__[50];
} ndim_;

#define ndim_1 ndim_

struct {
    doublecomplex storc[10000];
    doublereal storf[10000];
    integer stori[10000];
    logical storl[10000];
    integer nstorc, nstorf, nstori, nstorl, this__;
} storage_;

#define storage_1 storage_

struct {
    doublereal rdc[400000]	/* was [200][200][10] */, ccin[2000]	/* 
	    was [200][10] */, vdc[2000]	/* was [200][10] */, gm[400000]	/* 
	    was [200][200][10] */, ccgm[2000]	/* was [200][10] */, ccgmd[
	    2000]	/* was [200][10] */, ccli[2000]	/* was [200][10] */, 
	    ggin[2000]	/* was [200][10] */, ca[200], cdctr[700]	/* 
	    was [10][70] */, cdctro[700]	/* was [10][70] */;
    integer mbus[10];
    logical idealss[10], enabccin[2000]	/* was [200][10] */;
} s0_;

#define s0_1 s0_

struct {
    doublereal time, delt, print, fintim;
    logical timezero, firststep, laststep, onstep;
} s1_;

#define s1_1 s1_

struct {
    doublereal stor[50000];
    integer nexc;
} s2_;

#define s2_1 s2_

struct {
    doublereal var[1], con[100], pgb[1030];
    logical update_ag__;
} s4_;

#define s4_1 s4_

struct {
    doublereal cbr[20000]	/* was [2000][10] */, ccbr[20000]	/* 
	    was [2000][10] */, ccbrd[20000]	/* was [2000][10] */, ebr[
	    20000]	/* was [2000][10] */, ebrd[20000]	/* was [2000][
	    10] */, ebron[20000]	/* was [2000][10] */, ebrof[20000]	
	    /* was [2000][10] */, swlevl[20000]	/* was [2000][10] */, geq[
	    20000]	/* was [2000][10] */, geqon[20000]	/* was [2000][
	    10] */, geqof[20000]	/* was [2000][10] */, geqd[20000]	
	    /* was [2000][10] */, rlg[20000]	/* was [2000][10] */, rcg[
	    20000]	/* was [2000][10] */, rcl[20000]	/* was [2000][
	    10] */, rsc[20000]	/* was [2000][10] */, rsl[20000]	/* 
	    was [2000][10] */, ccl[20000]	/* was [2000][10] */, ccld[
	    20000]	/* was [2000][10] */, ccc[20000]	/* was [2000][
	    10] */, cccd[20000]	/* was [2000][10] */, g2l[20000]	/* 
	    was [2000][10] */, g2c[20000]	/* was [2000][10] */, v12l[
	    20000]	/* was [2000][10] */, v20l[20000]	/* was [2000][
	    10] */;
    integer nsw[10], brnsw[20000]	/* was [2000][10] */, iet[20000]	
	    /* was [2000][10] */, ief[20000]	/* was [2000][10] */, thisbr[
	    20000]	/* was [2000][10] */;
    logical resistor[20000]	/* was [2000][10] */, inductor[20000]	/* 
	    was [2000][10] */, capacitr[20000]	/* was [2000][10] */, source[
	    20000]	/* was [2000][10] */, switch__[20000]	/* was [2000][
	    10] */, idealbr[20000]	/* was [2000][10] */, openbr[20000]	
	    /* was [2000][10] */, defrdbr[20000]	/* was [2000][10] */, 
	    flipidlbr[20000]	/* was [2000][10] */, geqchange[2000];
} branches_;

#define branches_1 branches_

struct {
    doublecomplex stoc[20000];
    doublereal stof[20000];
    integer stoi[20000], txfr[400]	/* was [100][4] */, nstol, nstoi, 
	    nstof, nstoc, ntxfr, nvar, npgb, nnode, nsubs, nbrch[10], nxfmr, 
	    node[2000], subs[1000], testss[2000];
    logical stol[20000], guisoc;
    char ss_ref_style__[3];
} pscadv3_;

#define pscadv3_1 pscadv3_

struct {
    char dumlin[72], section[72], filename[72];
    integer iunit, iunitout;
    logical netdata;
    char inam[34], tnam[34], inam1[34], onam[34], snam[34], rtsnam[34], mnam[
	    34], mapname[34];
} fnames_;

#define fnames_1 fnames_

struct {
    doublereal tx[50];
    integer txrx[500], ntxrx;
} radiolinks_;

#define radiolinks_1 radiolinks_

/* ======================================================================= */
/* Generated by  : PSCAD v4.2.1 */

/* Warning:  The content of this file is automatically generated. */
/*           Do not modify, as any changes made here will be lost! */
/* ----------------------------------------------------------------------- */
/* Component     : Main */
/* Description   : */
/* ----------------------------------------------------------------------- */
/* ======================================================================= */
/* Subroutine */ int dsdyn_()
{
    /* Builtin functions */
    /* Subroutine */ int s_copy();

    /* Local variables */
    extern /* Subroutine */ int emtdc_openfile__(), emtdc_closefile__(), 
	    emtdc_gotosection__();

/* --------------------------------------- */
/* Standard includes */
/* --------------------------------------- */
/*     -------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING THE SIZE OF THE SYSTEM */
/*     -------------------------------------------------- */
/*     ND1  = MAX. NO. NODES PER SUBSYSTEM */
/*     ND2  = MAX. NO. SUBSYSTEMS */
/*     ND7  = MAX. NO. SUBSYSTEMS IN ALL PAGES */

/*     ---------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING TRANSFORMERS */
/*     ---------------------------------------- */
/*     ND3  = MAX. NO. MUTUALLY COUPLED WINDINGS, */
/*     ND4  = MAX. NO. TRANSFORMERS */

/*     ---------------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING DISTRIBUTED TRANSMISSION LINES */
/*     ---------------------------------------------------------- */
/*     ND5  = MAX. NO. OF MODES OR PHASES */
/*     ND6  = MAX. NO. OF LINES */
/*     ND8  = MAX. NO. OF POLES FOR FREQDEP MODEL */

/*     ---------------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING UMEC TRANSFORMER */
/*     (CURRENTLY UNUSED) */
/*     ---------------------------------------------------------- */

/*     -------------------------------------------- */
/*     PARAMETER FOR COMMON BLOCK S2 ( STOR(), NEXC */
/*     -------------------------------------------- */
/*     ND10  = MAX. NO. STOR LOCATIONS */

/*     -------------------------------------------------- */
/*     PARAMETERS FOR COMMON BLOCK S4 ( VAR(),CON(),PGB() */
/*     -------------------------------------------------- */
/*     ND11  = MAX. NO. VAR'S */
/*     ND12  = MAX. NO. CON'S */
/*     ND13  = MAX. NO. PGB'S */

/*     ----------------------------------------------------------- */
/*     PARAMETERS FOR THE MAXIMUM NUMBER OF BRANCHES PER SUBSYSTEM */
/*     ----------------------------------------------------------- */
/*     ND14  = MAX. NO. OF POSITIVE NUMBERED BRANCHES (obsolete) */
/*     ND15  = MAX. NO. OF NUMBERED BRANCHES */
/*     ND16  = MAX. NO. OF THEVININ SOURCES (obsolete) */

/*     ------------------------------------------------------------- */
/*     PARAMETERS FOR THE MAXIMUM NUMBER OF INTERPOLATING SWITCHINGS */
/*     PER SUBSYSTEM */
/*     ------------------------------------------------------------- */
/*     ND17  = MAX. NO. OF ALLOWABLE SWITCHING SUBROUTINES USING */
/*             INTERPOLATION PER SUBSYSTEM (Obsolete) */

/*     ------------------------------------------------------------- */
/*     PARAMETER FOR THE MAXIMUM NUMBER OF B6P110 VALVE GROUP MODELS */
/*     ------------------------------------------------------------- */
/*     ND18  = MAX. NO. OF B6P110 VALVE GROUP MODELS */

/*     ------------------------------------------------------------- */
/*     PARAMETER FOR THE MAXIMUM NUMBER OF ELEMENTS IN THE LOWER */
/*     TRIANGULARIZED CONDUCTANCE MATRIX PER SUBSYSTEM */

/*     A FULL MATRIX WOULD HAVE A MAXIMUM OF ( N*N - N ) / 2 ELEMENTS */
/*     WHERE N IS THE NUMBER OF NODES IN THE SUBSYSTEM */
/*     ------------------------------------------------------------- */
/*     ND19  = MAX. NO. OF SPARSITY ENTRIES PER SUBSYSTEM */

/* Node Map */
/* Pages */
/* NSTOL */
/* NSTOI */
/* NSTOF */
/* NSTOC */
/* NSTORL */
/* NSTORI */
/* NSTORF */
/* NSTORC */
/* TOTAL # OF TRAVELLING WAVE BUFFERS */
/* TOTAL # OF TERMS OF CONSTANT TRANSFORM */
/* TOTAL # OF POLES FOR TRANSFORM */
/* TOTAL # OF POLES FOR ATTENUATION */
/* TOTAL # OF POLES FOR SURGE IMPEDANCE */
/* TOTAL # OF MODES FOR BERGERON/FRE-DEP MOD */
/* TOTAL # OF WIRELESS RADIO TRANSMITTERS */
/* TOTAL # OF WIRELESS RADIO TRANSMITTERS & */
/* TOTAL # OF SPARSE ENTRIES IN 'DU' (HAMONI */
/* Phase Domain Model Dimensions */
/* TOTAL # OF NODES */
/* MAXIMUM NUMBER OF PHASE DOMAIN TLINES */
/* TOTAL   # OF MODES (PHASE DOMAIN) */
/* MAXIMUM # OF MODES (PHASE DOMAIN) */
/* TOTAL   # OF TRAVELLING WAVE BUFFERS (PHA */
/* TOTAL   # OF PROPAGATION BUFFERS (PHASE D */
/* TOTAL   # OF HSERC ELEMENTS (PHASE DOMAIN */
/* TOTAL   # OF YCSERC ELEMENTS (PHASE DOMAI */
/* TOTAL   # OF XHK ELEMENTS (PHASE DOMAIN) */
/* MAXIMUM NUMBER OF POLE/ZEROES (PHASE DOMA */
/* COMMON BLOCK */
/* Spare */
/* ====================================================================== */
/* EMTDC Constants */
/* ====================================================================== */
/* *** */
/* * Values of PI, its fractions and multiples */
/* *** */
/* *** */
/* * Sqare roots */
/* *** */
/* *** */
/* * 1/3 and 2/3 */
/* *** */
/* Type conversion routines */
/* ====================================================================== */
/* ====================================================================== */
/* Common block variables for EMTDC model data STORage */
/* ====================================================================== */
/* STORage Array index usage counters */
/* STORage Arrays (Temporary sizes) */
/* storage: STORx */
/* Logical */
/* Integer */
/* Real */
/* Common Block for EMTDC model data storage */
/* Complex */
/*     CDCTRO = Total winding current including saturation current */
/* TIME    : current time of simulation in seconds */
/* DELT    : simulation time step in seconds */
/* ICH     : Obsolete */
/* PRINT   : print step interval in seconds */
/* FINTIM  : simulation finish tim ein seconds */
/* TIMEZERO: true when time is zero */
/* FIRSTSTEP: true for first step starting from data file or snap file */
/* LASTSTEP: true for last step of the run */
/* ONSTEP:   true if calling from dsdyn/dsout */
/* Data storage array for backward compatibility */
/* Real data storage ( from V3.0 version ) */
/* Running index of STOR array */
/* ======================================================================= */
/* Branch Types (Constants) */
/* ======================================================================= */
/* Breakers */
/* Power Electronic Switches (PESWITCH type) */
/* SWINT5 Breaker */
/* Diode */
/* Thyistor */
/* GTO */
/* IGBT */
/* MOSFET */
/* Arrestors */
/* Transistor */
/* Voltage Sources */
/* Gapless Metal Oxide Arrestor */
/* Current Sources */
/* Branch voltage source */
/* Single phase current source */
/* ======================================================================= */
/* Common Blocks */
/* ======================================================================= */
/* Three phase current source */
/* Branch current */
/* Equivalent history current */
/* Equivalent history current from step */
/* Internal voltage magnitude */
/* EBR from previous time step */
/* ON state resistance */
/* OFF state resistance */
/* Switching level (I,V,or time) */
/* Equivalent conductance */
/* Equivalent ON state conductance */
/* Equivalent OFF state conductance */
/* Equivalent conductance from last step */
/* Factor used in collapsing RLC branch */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/* Total # of switched in SS */
/* Branch # ( switch => branch ) */
/* From node of branch +ve curr. flows o */
/* To node of branch, +ve curr. flows in */
/* Starting location of data storage */
/* True if has resistance */
/* True if has inductance */
/* True if has capacitance */
/* True if has internal source */
/* True if switchable */
/* True if zero impedance (ideal) */
/* True if switch is open (high R) */
/* True if attributes undecided */
/* Flag if an ideal branch is collapsed */
/* True if branch switched w/o interp */
/* =============================================================================== */
/* Common block variables */
/* =============================================================================== */
/* Array index usage counters */
/* Storage: STOx */
/* Control, Monitor */
/* Node, Transformer */
/* Subsystems */
/* DSDYN <-> DSOUT tran */
/* Storage Arrays */
/* Branch */
/* Temporary sizes */
/* Operational Mode */
/* true: Socket exists */
/* Common Block for PSCAD V3 linkage */
/*  NAMES OF ALL INPUT / OUTPUT FILES */
/*  INAM  =  INPUT FILE NAME ( SNAPSHOT OR DATA FILES ) */
/*  TNAM  =  TABLE FILE NAME ( Nodes Table file ) */
/*  INAM1 =  INPUT INCLUDE FILE NAME */
/*  FILENAME =  DATA FILE NAME */
/*  MAPNAME  = Name of the map to be read for this page */
/*  IUNIT =  CURRENT INPUT FILE UNIT NUMBER */
/*  IUNITOUT = STARTING UNIT # FOR OUTPUT FILES */
/*  ONAM  =  OUTPUT FILE NAME ( PGB INFORMATION AND/OR PRINT PLOTS ) */
/*  SNAM  =  END OF RUN SNAPSHOT FILE NAME */
/*           SNAM IF ONLY 1 SNAP TO BE WRITTEN OR MULTIPLE TO SAME FILE */
/*           SNAP-01,SNAP-02 ...  IF INCREMENTAL SNAP TO DIFFERENT FILE */
/*  RTSNAM = Same as SNAM but for runtime snapshot files */
/*  MNAM  =  MULTIPLE RUN FILE NAME */
/*  DUMLIN=  ARRAY USED FOR STORING CURRENT DATA LINE READ */
/*  SECTION= Name of the section last read */
/*  DATALINE = True if nodes from map file are to be read */
/* true while reading network data */
/* --------------------------------------- */
/* Variable Declarations */
/* --------------------------------------- */
/* Subroutine Parameters */
/* Electrical Node Indexes */
/* Control Signals */
/* Internal Variables */
/* Indexing variables */
/* --------------------------------------- */
/* Record local indexes */
/* --------------------------------------- */
/* Dsdyn <-> Dsout transfer index storage */
/* SS/Node/Branch/Xfmr */
#line 55 "Main.f"
    ++pscadv3_1.ntxfr;
#line 56 "Main.f"
    pscadv3_1.txfr[pscadv3_1.ntxfr - 1] = pscadv3_1.nstol;
#line 57 "Main.f"
    pscadv3_1.txfr[pscadv3_1.ntxfr + 99] = pscadv3_1.nstoi;
#line 58 "Main.f"
    pscadv3_1.txfr[pscadv3_1.ntxfr + 199] = pscadv3_1.nstof;
/* Record Offset and Increment Storage Counters */
#line 61 "Main.f"
    pscadv3_1.nnode += 2;
/* --------------------------------------- */
/* Transfers from storage arrays */
/* --------------------------------------- */
/* --------------------------------------- */
/* Transfer from Imports */
/* --------------------------------------- */
/* --------------------------------------- */
/* Electrical Node Lookup */
/* --------------------------------------- */
/* --------------------------------------- */
/* Read Model data (if any) */
/* --------------------------------------- */
#line 83 "Main.f"
    if (s1_1.timezero) {
#line 84 "Main.f"
	s_copy(fnames_1.filename, "Main.dta", (ftnlen)72, (ftnlen)8);
#line 85 "Main.f"
	emtdc_openfile__();
#line 86 "Main.f"
	s_copy(fnames_1.section, "DATADSD:", (ftnlen)72, (ftnlen)8);
#line 87 "Main.f"
	emtdc_gotosection__();
#line 88 "Main.f"
    }
/* --------------------------------------- */
/* Generated code from module definition */
/* --------------------------------------- */
/* --------------------------------------- */
/* Feedbacks and transfers to storage */
/* --------------------------------------- */
/* --------------------------------------- */
/* Transfer to Exports */
/* --------------------------------------- */
/* --------------------------------------- */
/* Close Model Data read */
/* --------------------------------------- */
#line 108 "Main.f"
    if (s1_1.timezero) {
#line 108 "Main.f"
	emtdc_closefile__();
#line 108 "Main.f"
    }
#line 109 "Main.f"
    return 0;
} /* dsdyn_ */

/* ======================================================================= */
/* Subroutine */ int dsout_()
{
    /* Builtin functions */
    /* Subroutine */ int s_copy();

    /* Local variables */
    static integer istof, istoi, istol;
    extern /* Subroutine */ int emtdc_openfile__(), emtdc_closefile__(), 
	    emtdc_gotosection__();

/* --------------------------------------- */
/* Standard includes */
/* --------------------------------------- */
/*     -------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING THE SIZE OF THE SYSTEM */
/*     -------------------------------------------------- */
/*     ND1  = MAX. NO. NODES PER SUBSYSTEM */
/*     ND2  = MAX. NO. SUBSYSTEMS */
/*     ND7  = MAX. NO. SUBSYSTEMS IN ALL PAGES */

/*     ---------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING TRANSFORMERS */
/*     ---------------------------------------- */
/*     ND3  = MAX. NO. MUTUALLY COUPLED WINDINGS, */
/*     ND4  = MAX. NO. TRANSFORMERS */

/*     ---------------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING DISTRIBUTED TRANSMISSION LINES */
/*     ---------------------------------------------------------- */
/*     ND5  = MAX. NO. OF MODES OR PHASES */
/*     ND6  = MAX. NO. OF LINES */
/*     ND8  = MAX. NO. OF POLES FOR FREQDEP MODEL */

/*     ---------------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING UMEC TRANSFORMER */
/*     (CURRENTLY UNUSED) */
/*     ---------------------------------------------------------- */

/*     -------------------------------------------- */
/*     PARAMETER FOR COMMON BLOCK S2 ( STOR(), NEXC */
/*     -------------------------------------------- */
/*     ND10  = MAX. NO. STOR LOCATIONS */

/*     -------------------------------------------------- */
/*     PARAMETERS FOR COMMON BLOCK S4 ( VAR(),CON(),PGB() */
/*     -------------------------------------------------- */
/*     ND11  = MAX. NO. VAR'S */
/*     ND12  = MAX. NO. CON'S */
/*     ND13  = MAX. NO. PGB'S */

/*     ----------------------------------------------------------- */
/*     PARAMETERS FOR THE MAXIMUM NUMBER OF BRANCHES PER SUBSYSTEM */
/*     ----------------------------------------------------------- */
/*     ND14  = MAX. NO. OF POSITIVE NUMBERED BRANCHES (obsolete) */
/*     ND15  = MAX. NO. OF NUMBERED BRANCHES */
/*     ND16  = MAX. NO. OF THEVININ SOURCES (obsolete) */

/*     ------------------------------------------------------------- */
/*     PARAMETERS FOR THE MAXIMUM NUMBER OF INTERPOLATING SWITCHINGS */
/*     PER SUBSYSTEM */
/*     ------------------------------------------------------------- */
/*     ND17  = MAX. NO. OF ALLOWABLE SWITCHING SUBROUTINES USING */
/*             INTERPOLATION PER SUBSYSTEM (Obsolete) */

/*     ------------------------------------------------------------- */
/*     PARAMETER FOR THE MAXIMUM NUMBER OF B6P110 VALVE GROUP MODELS */
/*     ------------------------------------------------------------- */
/*     ND18  = MAX. NO. OF B6P110 VALVE GROUP MODELS */

/*     ------------------------------------------------------------- */
/*     PARAMETER FOR THE MAXIMUM NUMBER OF ELEMENTS IN THE LOWER */
/*     TRIANGULARIZED CONDUCTANCE MATRIX PER SUBSYSTEM */

/*     A FULL MATRIX WOULD HAVE A MAXIMUM OF ( N*N - N ) / 2 ELEMENTS */
/*     WHERE N IS THE NUMBER OF NODES IN THE SUBSYSTEM */
/*     ------------------------------------------------------------- */
/*     ND19  = MAX. NO. OF SPARSITY ENTRIES PER SUBSYSTEM */

/* Node Map */
/* Pages */
/* NSTOL */
/* NSTOI */
/* NSTOF */
/* NSTOC */
/* NSTORL */
/* NSTORI */
/* NSTORF */
/* NSTORC */
/* TOTAL # OF TRAVELLING WAVE BUFFERS */
/* TOTAL # OF TERMS OF CONSTANT TRANSFORM */
/* TOTAL # OF POLES FOR TRANSFORM */
/* TOTAL # OF POLES FOR ATTENUATION */
/* TOTAL # OF POLES FOR SURGE IMPEDANCE */
/* TOTAL # OF MODES FOR BERGERON/FRE-DEP MOD */
/* TOTAL # OF WIRELESS RADIO TRANSMITTERS */
/* TOTAL # OF WIRELESS RADIO TRANSMITTERS & */
/* TOTAL # OF SPARSE ENTRIES IN 'DU' (HAMONI */
/* Phase Domain Model Dimensions */
/* TOTAL # OF NODES */
/* MAXIMUM NUMBER OF PHASE DOMAIN TLINES */
/* TOTAL   # OF MODES (PHASE DOMAIN) */
/* MAXIMUM # OF MODES (PHASE DOMAIN) */
/* TOTAL   # OF TRAVELLING WAVE BUFFERS (PHA */
/* TOTAL   # OF PROPAGATION BUFFERS (PHASE D */
/* TOTAL   # OF HSERC ELEMENTS (PHASE DOMAIN */
/* TOTAL   # OF YCSERC ELEMENTS (PHASE DOMAI */
/* TOTAL   # OF XHK ELEMENTS (PHASE DOMAIN) */
/* MAXIMUM NUMBER OF POLE/ZEROES (PHASE DOMA */
/* COMMON BLOCK */
/* Spare */
/* ====================================================================== */
/* EMTDC Constants */
/* ====================================================================== */
/* *** */
/* * Values of PI, its fractions and multiples */
/* *** */
/* *** */
/* * Sqare roots */
/* *** */
/* *** */
/* * 1/3 and 2/3 */
/* *** */
/* Type conversion routines */
/* ====================================================================== */
/* ====================================================================== */
/* Common block variables for EMTDC model data STORage */
/* ====================================================================== */
/* STORage Array index usage counters */
/* STORage Arrays (Temporary sizes) */
/* storage: STORx */
/* Logical */
/* Integer */
/* Real */
/* Common Block for EMTDC model data storage */
/* Complex */
/*     CDCTRO = Total winding current including saturation current */
/* TIME    : current time of simulation in seconds */
/* DELT    : simulation time step in seconds */
/* ICH     : Obsolete */
/* PRINT   : print step interval in seconds */
/* FINTIM  : simulation finish tim ein seconds */
/* TIMEZERO: true when time is zero */
/* FIRSTSTEP: true for first step starting from data file or snap file */
/* LASTSTEP: true for last step of the run */
/* ONSTEP:   true if calling from dsdyn/dsout */
/* Data storage array for backward compatibility */
/* Real data storage ( from V3.0 version ) */
/* Running index of STOR array */
/* ======================================================================= */
/* Branch Types (Constants) */
/* ======================================================================= */
/* Breakers */
/* Power Electronic Switches (PESWITCH type) */
/* SWINT5 Breaker */
/* Diode */
/* Thyistor */
/* GTO */
/* IGBT */
/* MOSFET */
/* Arrestors */
/* Transistor */
/* Voltage Sources */
/* Gapless Metal Oxide Arrestor */
/* Current Sources */
/* Branch voltage source */
/* Single phase current source */
/* ======================================================================= */
/* Common Blocks */
/* ======================================================================= */
/* Three phase current source */
/* Branch current */
/* Equivalent history current */
/* Equivalent history current from step */
/* Internal voltage magnitude */
/* EBR from previous time step */
/* ON state resistance */
/* OFF state resistance */
/* Switching level (I,V,or time) */
/* Equivalent conductance */
/* Equivalent ON state conductance */
/* Equivalent OFF state conductance */
/* Equivalent conductance from last step */
/* Factor used in collapsing RLC branch */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/* Total # of switched in SS */
/* Branch # ( switch => branch ) */
/* From node of branch +ve curr. flows o */
/* To node of branch, +ve curr. flows in */
/* Starting location of data storage */
/* True if has resistance */
/* True if has inductance */
/* True if has capacitance */
/* True if has internal source */
/* True if switchable */
/* True if zero impedance (ideal) */
/* True if switch is open (high R) */
/* True if attributes undecided */
/* Flag if an ideal branch is collapsed */
/* True if branch switched w/o interp */
/* =============================================================================== */
/* Common block variables */
/* =============================================================================== */
/* Array index usage counters */
/* Storage: STOx */
/* Control, Monitor */
/* Node, Transformer */
/* Subsystems */
/* DSDYN <-> DSOUT tran */
/* Storage Arrays */
/* Branch */
/* Temporary sizes */
/* Operational Mode */
/* true: Socket exists */
/* Common Block for PSCAD V3 linkage */
/*  NAMES OF ALL INPUT / OUTPUT FILES */
/*  INAM  =  INPUT FILE NAME ( SNAPSHOT OR DATA FILES ) */
/*  TNAM  =  TABLE FILE NAME ( Nodes Table file ) */
/*  INAM1 =  INPUT INCLUDE FILE NAME */
/*  FILENAME =  DATA FILE NAME */
/*  MAPNAME  = Name of the map to be read for this page */
/*  IUNIT =  CURRENT INPUT FILE UNIT NUMBER */
/*  IUNITOUT = STARTING UNIT # FOR OUTPUT FILES */
/*  ONAM  =  OUTPUT FILE NAME ( PGB INFORMATION AND/OR PRINT PLOTS ) */
/*  SNAM  =  END OF RUN SNAPSHOT FILE NAME */
/*           SNAM IF ONLY 1 SNAP TO BE WRITTEN OR MULTIPLE TO SAME FILE */
/*           SNAP-01,SNAP-02 ...  IF INCREMENTAL SNAP TO DIFFERENT FILE */
/*  RTSNAM = Same as SNAM but for runtime snapshot files */
/*  MNAM  =  MULTIPLE RUN FILE NAME */
/*  DUMLIN=  ARRAY USED FOR STORING CURRENT DATA LINE READ */
/*  SECTION= Name of the section last read */
/*  DATALINE = True if nodes from map file are to be read */
/* true while reading network data */
/* --------------------------------------- */
/* Variable Declarations */
/* --------------------------------------- */
/* Electrical Node Indexes */
/* Control Signals */
/* Internal Variables */
/* Indexing variables */
/* Storage Indexes */
/* --------------------------------------- */
/* Record local indexes */
/* --------------------------------------- */
/* Dsdyn <-> Dsout transfer index storage */
/* SS/Node/Branch/Xfmr */
#line 154 "Main.f"
    ++pscadv3_1.ntxfr;
#line 155 "Main.f"
    istol = pscadv3_1.txfr[pscadv3_1.ntxfr - 1];
#line 156 "Main.f"
    istoi = pscadv3_1.txfr[pscadv3_1.ntxfr + 99];
#line 157 "Main.f"
    istof = pscadv3_1.txfr[pscadv3_1.ntxfr + 199];
/* Record Offset and Increment Storage Counters */
#line 160 "Main.f"
    pscadv3_1.nnode += 2;
/* --------------------------------------- */
/* Transfers from storage arrays */
/* --------------------------------------- */
/* --------------------------------------- */
/* Electrical Node Lookup */
/* --------------------------------------- */
/* --------------------------------------- */
/* Read Model data (if any) */
/* --------------------------------------- */
#line 177 "Main.f"
    if (s1_1.timezero) {
#line 178 "Main.f"
	s_copy(fnames_1.filename, "Main.dta", (ftnlen)72, (ftnlen)8);
#line 179 "Main.f"
	emtdc_openfile__();
#line 180 "Main.f"
	s_copy(fnames_1.section, "DATADSO:", (ftnlen)72, (ftnlen)8);
#line 181 "Main.f"
	emtdc_gotosection__();
#line 182 "Main.f"
    }
/* --------------------------------------- */
/* Generated code from module definition */
/* --------------------------------------- */
/* --------------------------------------- */
/* Feedbacks and transfers to storage */
/* --------------------------------------- */
/* --------------------------------------- */
/* Close Model Data read */
/* --------------------------------------- */
#line 198 "Main.f"
    if (s1_1.timezero) {
#line 198 "Main.f"
	emtdc_closefile__();
#line 198 "Main.f"
    }
#line 199 "Main.f"
    return 0;
} /* dsout_ */

