!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
      REAL    DERIV1        ! Derivative Function
      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'
      REAL    REALPOLE      ! Real Pole

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, RT_11
      REAL     RT_12, RT_13, RT_14, RT_15, RT_16
      REAL     RT_17, RT_18, RT_19, RT_20, RT_21
      REAL     RT_22, RT_23, RT_24, RT_25, RT_26
      REAL     RT_27, RT_28, RT_29, RT_30, RT_31
      REAL     RT_32, RT_33, RT_34, RT_35, RT_36
      REAL     RT_37, RT_38

! Internal Variables
      REAL     RVD2_1(2), RVD1_1, RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 38
      IPGB      = NPGB
      NPGB      = NPGB + 17
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      RT_3     = STOF(ISTOF + 3)
      RT_4     = STOF(ISTOF + 4)
      RT_5     = STOF(ISTOF + 5)
      RT_6     = STOF(ISTOF + 6)
      RT_7     = STOF(ISTOF + 7)
      RT_8     = STOF(ISTOF + 8)
      RT_9     = STOF(ISTOF + 9)
      RT_10    = STOF(ISTOF + 10)
      RT_11    = STOF(ISTOF + 11)
      RT_12    = STOF(ISTOF + 12)
      RT_13    = STOF(ISTOF + 13)
      RT_14    = STOF(ISTOF + 14)
      RT_15    = STOF(ISTOF + 15)
      RT_16    = STOF(ISTOF + 16)
      RT_17    = STOF(ISTOF + 17)
      RT_18    = STOF(ISTOF + 18)
      RT_19    = STOF(ISTOF + 19)
      RT_20    = STOF(ISTOF + 20)
      RT_21    = STOF(ISTOF + 21)
      RT_22    = STOF(ISTOF + 22)
      RT_23    = STOF(ISTOF + 23)
      RT_24    = STOF(ISTOF + 24)
      RT_25    = STOF(ISTOF + 25)
      RT_26    = STOF(ISTOF + 26)
      RT_27    = STOF(ISTOF + 27)
      RT_28    = STOF(ISTOF + 28)
      RT_29    = STOF(ISTOF + 29)
      RT_30    = STOF(ISTOF + 30)
      RT_31    = STOF(ISTOF + 31)
      RT_32    = STOF(ISTOF + 32)
      RT_33    = STOF(ISTOF + 33)
      RT_34    = STOF(ISTOF + 34)
      RT_35    = STOF(ISTOF + 35)
      RT_36    = STOF(ISTOF + 36)
      RT_37    = STOF(ISTOF + 37)
      RT_38    = STOF(ISTOF + 38)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[time-sig] Output of Simulation Time 
      RT_1 = TIME

! 20:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_1,0.0,0.0,1.0,RVD2_1)
      RT_2 = RVD2_1(1)

! 30:[gain] Gain Block 
!  Gain
      RT_3 = 3.0 * RT_2

! 40:[pgb] Output Channel 'RT_3'

      PGB(IPGB+1) = RT_3

! 50:[time-sig] Output of Simulation Time 
      RT_4 = TIME

! 60:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_4,0.0,0.0,1.0,RVD2_1)
      RT_5 = RVD2_1(1)

! 70:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_7 = DERIV1(RVD1_1,RT_5)
!

! 80:[gain] Gain Block 
!  Gain
      RT_6 = 3.0 * RT_7

! 90:[pgb] Output Channel 'RT_6'

      PGB(IPGB+2) = RT_6

! 100:[time-sig] Output of Simulation Time 
      RT_8 = TIME

! 110:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_8,0.0,0.0,1.0,RVD2_1)
      RT_9 = RVD2_1(1)

! 120:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_9
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_10 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 130:[pgb] Output Channel 'RT_10'

      PGB(IPGB+3) = RT_10

! 140:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_9
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_11 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 150:[realpole] Real Pole 
!  Real_Pole
      RT_12 = REALPOLE(0,1,0,3.0,2.37,RT_11,0.0,-1.0E20,1.0E20)

! 160:[pgb] Output Channel 'RT_12'

      PGB(IPGB+4) = RT_12

! 170:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_13 = DERIV1(RVD1_1,RT_9)
!

! 180:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_13
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_15 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 190:[pgb] Output Channel 'RT_15'

      PGB(IPGB+5) = RT_15

! 200:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_14 = DERIV1(RVD1_1,RT_9)
!

! 210:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_14
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_16 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 220:[realpole] Real Pole 
!  Real_Pole
      RT_17 = REALPOLE(0,1,0,3.0,2.37,RT_16,0.0,-1.0E20,1.0E20)

! 230:[pgb] Output Channel 'RT_17'

      PGB(IPGB+6) = RT_17

! 240:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_18 = DERIV1(RVD1_1,RT_9)
!

! 250:[pgb] Output Channel 'RT_18'

      PGB(IPGB+7) = RT_18

! 260:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_19 = DERIV1(RVD1_1,RT_9)
!

! 270:[realpole] Real Pole 
!  Real_Pole
      RT_20 = REALPOLE(0,1,0,3.0,2.37,RT_19,0.0,-1.0E20,1.0E20)

! 280:[pgb] Output Channel 'RT_20'

      PGB(IPGB+8) = RT_20

! 290:[realpole] Real Pole 
!  Real_Pole
      RT_21 = REALPOLE(0,1,0,3.0,2.37,RT_9,0.0,-1.0E20,1.0E20)

! 300:[pgb] Output Channel 'RT_21'

      PGB(IPGB+9) = RT_21

! 310:[realpole] Real Pole 
!  Real_Pole
      RT_22 = REALPOLE(0,1,0,1.0,2.73,RT_9,0.0,-1.0E20,1.0E20)

! 320:[realpole] Real Pole 
!  Real_Pole
      RT_23 = REALPOLE(0,1,0,3.0,2.37,RT_22,0.0,-1.0E20,1.0E20)

! 330:[pgb] Output Channel 'RT_23'

      PGB(IPGB+10) = RT_23

! 340:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_9,RT_24)

! 350:[pgb] Output Channel 'RT_24'

      PGB(IPGB+11) = RT_24

! 360:[time-sig] Output of Simulation Time 
      RT_28 = TIME

! 370:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_28,0.0,0.0,1.0,RVD2_1)
      RT_25 = RVD2_1(1)

! 380:[realpole] Real Pole 
!  Real_Pole
      RT_26 = REALPOLE(0,1,0,1.0,2.73,RT_25,0.0,-1.0E20,1.0E20)

! 390:[realpole] Real Pole 
!  Real_Pole
      RT_27 = REALPOLE(0,1,0,3.0,2.37,RT_26,0.0,-1.0E20,1.0E20)

! 400:[pgb] Output Channel 'RT_27'

      PGB(IPGB+12) = RT_27

! 410:[realpole] Real Pole 
!  Real_Pole
      RT_29 = REALPOLE(0,1,0,1.0,2.73,RT_25,0.0,-1.0E20,1.0E20)

! 420:[realpole] Real Pole 
!  Real_Pole
      RT_30 = REALPOLE(0,1,0,6.0,2.37,RT_29,0.0,-1.0E20,1.0E20)

! 430:[pgb] Output Channel 'RT_30'

      PGB(IPGB+13) = RT_30

! 440:[realpole] Real Pole 
!  Real_Pole
      RT_31 = REALPOLE(0,1,0,1.0,2.73,RT_25,0.0,-1.0E20,1.0E20)

! 450:[realpole] Real Pole 
!  Real_Pole
      RT_32 = REALPOLE(0,1,0,9.0,2.37,RT_31,0.0,-1.0E20,1.0E20)

! 460:[pgb] Output Channel 'RT_32'

      PGB(IPGB+14) = RT_32

! 470:[realpole] Real Pole 
!  Real_Pole
      RT_33 = REALPOLE(0,1,0,1.0,3.0,RT_25,0.0,-1.0E20,1.0E20)

! 480:[realpole] Real Pole 
!  Real_Pole
      RT_34 = REALPOLE(0,1,0,3.0,2.37,RT_33,0.0,-1.0E20,1.0E20)

! 490:[pgb] Output Channel 'RT_34'

      PGB(IPGB+15) = RT_34

! 500:[realpole] Real Pole 
!  Real_Pole
      RT_35 = REALPOLE(0,1,0,1.0,6.0,RT_25,0.0,-1.0E20,1.0E20)

! 510:[realpole] Real Pole 
!  Real_Pole
      RT_36 = REALPOLE(0,1,0,3.0,2.37,RT_35,0.0,-1.0E20,1.0E20)

! 520:[pgb] Output Channel 'RT_36'

      PGB(IPGB+16) = RT_36

! 530:[realpole] Real Pole 
!  Real_Pole
      RT_37 = REALPOLE(0,1,0,1.0,9.0,RT_25,0.0,-1.0E20,1.0E20)

! 540:[realpole] Real Pole 
!  Real_Pole
      RT_38 = REALPOLE(0,1,0,3.0,2.37,RT_37,0.0,-1.0E20,1.0E20)

! 550:[pgb] Output Channel 'RT_38'

      PGB(IPGB+17) = RT_38

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 3) = RT_3
      STOF(ISTOF + 4) = RT_4
      STOF(ISTOF + 5) = RT_5
      STOF(ISTOF + 6) = RT_6
      STOF(ISTOF + 7) = RT_7
      STOF(ISTOF + 8) = RT_8
      STOF(ISTOF + 9) = RT_9
      STOF(ISTOF + 10) = RT_10
      STOF(ISTOF + 11) = RT_11
      STOF(ISTOF + 12) = RT_12
      STOF(ISTOF + 13) = RT_13
      STOF(ISTOF + 14) = RT_14
      STOF(ISTOF + 15) = RT_15
      STOF(ISTOF + 16) = RT_16
      STOF(ISTOF + 17) = RT_17
      STOF(ISTOF + 18) = RT_18
      STOF(ISTOF + 19) = RT_19
      STOF(ISTOF + 20) = RT_20
      STOF(ISTOF + 21) = RT_21
      STOF(ISTOF + 22) = RT_22
      STOF(ISTOF + 23) = RT_23
      STOF(ISTOF + 24) = RT_24
      STOF(ISTOF + 25) = RT_25
      STOF(ISTOF + 26) = RT_26
      STOF(ISTOF + 27) = RT_27
      STOF(ISTOF + 28) = RT_28
      STOF(ISTOF + 29) = RT_29
      STOF(ISTOF + 30) = RT_30
      STOF(ISTOF + 31) = RT_31
      STOF(ISTOF + 32) = RT_32
      STOF(ISTOF + 33) = RT_33
      STOF(ISTOF + 34) = RT_34
      STOF(ISTOF + 35) = RT_35
      STOF(ISTOF + 36) = RT_36
      STOF(ISTOF + 37) = RT_37
      STOF(ISTOF + 38) = RT_38


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 17
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------



!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------



!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[time-sig] Output of Simulation Time 

! 20:[compare] Single Input Level Comparator 

! 30:[gain] Gain Block 

! 40:[pgb] Output Channel 'RT_3'

! 50:[time-sig] Output of Simulation Time 

! 60:[compare] Single Input Level Comparator 

! 70:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 80:[gain] Gain Block 

! 90:[pgb] Output Channel 'RT_6'

! 100:[time-sig] Output of Simulation Time 

! 110:[compare] Single Input Level Comparator 

! 120:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 130:[pgb] Output Channel 'RT_10'

! 140:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 150:[realpole] Real Pole 

! 160:[pgb] Output Channel 'RT_12'

! 170:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 180:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 190:[pgb] Output Channel 'RT_15'

! 200:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 210:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 220:[realpole] Real Pole 

! 230:[pgb] Output Channel 'RT_17'

! 240:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 250:[pgb] Output Channel 'RT_18'

! 260:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 270:[realpole] Real Pole 

! 280:[pgb] Output Channel 'RT_20'

! 290:[realpole] Real Pole 

! 300:[pgb] Output Channel 'RT_21'

! 310:[realpole] Real Pole 

! 320:[realpole] Real Pole 

! 330:[pgb] Output Channel 'RT_23'

! 340:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,2.73,0.0)

! 350:[pgb] Output Channel 'RT_24'

! 360:[time-sig] Output of Simulation Time 

! 370:[compare] Single Input Level Comparator 

! 380:[realpole] Real Pole 

! 390:[realpole] Real Pole 

! 400:[pgb] Output Channel 'RT_27'

! 410:[realpole] Real Pole 

! 420:[realpole] Real Pole 

! 430:[pgb] Output Channel 'RT_30'

! 440:[realpole] Real Pole 

! 450:[realpole] Real Pole 

! 460:[pgb] Output Channel 'RT_32'

! 470:[realpole] Real Pole 

! 480:[realpole] Real Pole 

! 490:[pgb] Output Channel 'RT_34'

! 500:[realpole] Real Pole 

! 510:[realpole] Real Pole 

! 520:[pgb] Output Channel 'RT_36'

! 530:[realpole] Real Pole 

! 540:[realpole] Real Pole 

! 550:[pgb] Output Channel 'RT_38'

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


      RETURN
      END

