!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
      REAL    DERIV1        ! Derivative Function
      REAL    REALPOLE      ! Real Pole
      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, RT_11
      REAL     RT_12, RT_13, RT_14, RT_15, RT_16
      REAL     RT_17, RT_18, RT_19, RT_20, RT_21
      REAL     RT_22, RT_23, RT_24, RT_25, RT_26
      REAL     RT_27, RT_28, RT_29, RT_30, RT_31
      REAL     RT_32, RT_33, RT_34, RT_35, RT_36
      REAL     RT_37, RT_38, RT_39, RT_40, RT_41
      REAL     RT_42, RT_43, RT_44, RT_45, RT_46
      REAL     RT_47, RT_48, RT_49, RT_50, RT_51
      REAL     RT_52, RT_53, RT_54, RT_55, RT_56
      REAL     RT_57, RT_58, RT_59, RT_60, RT_61
      REAL     RT_62, RT_63, RT_64, RT_65, RT_66
      REAL     RT_67, RT_68, RT_69, RT_70, RT_71
      REAL     RT_72, RT_73, RT_74, RT_75, RT_76
      REAL     RT_77, RT_78, RT_79, RT_80, RT_81
      REAL     RT_82, RT_83, RT_84, RT_85, RT_86
      REAL     RT_87, RT_88, RT_89, RT_90, RT_91
      REAL     RT_92, RT_93, RT_94, RT_95, RT_96
      REAL     RT_97, RT_98, RT_99, RT_100
      REAL     RT_101, RT_102, RT_103, RT_104
      REAL     RT_105, RT_106, RT_107, RT_108
      REAL     RT_109, RT_110, RT_111, RT_112
      REAL     RT_113, RT_114, RT_115, RT_116
      REAL     RT_117, RT_118, RT_119, RT_120
      REAL     RT_121, RT_122, RT_123, RT_124
      REAL     RT_125, RT_126, RT_127, RT_128
      REAL     RT_129, RT_130, RT_131, RT_132
      REAL     RT_133, RT_134, RT_135, RT_136
      REAL     RT_137, RT_138, RT_139, RT_140
      REAL     RT_141, RT_142, RT_143, RT_144
      REAL     RT_145, RT_146, RT_147, RT_148
      REAL     RT_149, RT_150, RT_151, RT_152
      REAL     RT_153, RT_154, RT_155, RT_156
      REAL     RT_157, RT_158, RT_159, RT_160
      REAL     RT_161, RT_162, RT_163, RT_164
      REAL     RT_165, RT_166, RT_167, RT_168
      REAL     RT_169, RT_170, RT_171, RT_172
      REAL     RT_173, RT_174, RT_175, RT_176
      REAL     RT_177, RT_178, RT_179, RT_180
      REAL     RT_181, RT_182, RT_183, RT_184
      REAL     RT_185, RT_186, RT_187, RT_188
      REAL     RT_189, RT_190, RT_191, RT_192
      REAL     RT_193, RT_194, RT_195, RT_196
      REAL     RT_197, RT_198, RT_199, RT_200
      REAL     RT_201, RT_202, RT_203, RT_204
      REAL     RT_205, RT_206, RT_207, RT_208
      REAL     RT_209, RT_210, RT_211, RT_212
      REAL     RT_213, RT_214, RT_215, RT_216
      REAL     RT_217, RT_218, RT_219, RT_220
      REAL     RT_221, RT_222, RT_223, RT_224
      REAL     RT_225, RT_226, RT_227, RT_228
      REAL     RT_229, RT_230, RT_231

! Internal Variables
      REAL     RVD2_1(2), RVD1_1, RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 231
      IPGB      = NPGB
      NPGB      = NPGB + 94
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      RT_3     = STOF(ISTOF + 3)
      RT_4     = STOF(ISTOF + 4)
      RT_5     = STOF(ISTOF + 5)
      RT_6     = STOF(ISTOF + 6)
      RT_7     = STOF(ISTOF + 7)
      RT_8     = STOF(ISTOF + 8)
      RT_9     = STOF(ISTOF + 9)
      RT_10    = STOF(ISTOF + 10)
      RT_11    = STOF(ISTOF + 11)
      RT_12    = STOF(ISTOF + 12)
      RT_13    = STOF(ISTOF + 13)
      RT_14    = STOF(ISTOF + 14)
      RT_15    = STOF(ISTOF + 15)
      RT_16    = STOF(ISTOF + 16)
      RT_17    = STOF(ISTOF + 17)
      RT_18    = STOF(ISTOF + 18)
      RT_19    = STOF(ISTOF + 19)
      RT_20    = STOF(ISTOF + 20)
      RT_21    = STOF(ISTOF + 21)
      RT_22    = STOF(ISTOF + 22)
      RT_23    = STOF(ISTOF + 23)
      RT_24    = STOF(ISTOF + 24)
      RT_25    = STOF(ISTOF + 25)
      RT_26    = STOF(ISTOF + 26)
      RT_27    = STOF(ISTOF + 27)
      RT_28    = STOF(ISTOF + 28)
      RT_29    = STOF(ISTOF + 29)
      RT_30    = STOF(ISTOF + 30)
      RT_31    = STOF(ISTOF + 31)
      RT_32    = STOF(ISTOF + 32)
      RT_33    = STOF(ISTOF + 33)
      RT_34    = STOF(ISTOF + 34)
      RT_35    = STOF(ISTOF + 35)
      RT_36    = STOF(ISTOF + 36)
      RT_37    = STOF(ISTOF + 37)
      RT_38    = STOF(ISTOF + 38)
      RT_39    = STOF(ISTOF + 39)
      RT_40    = STOF(ISTOF + 40)
      RT_41    = STOF(ISTOF + 41)
      RT_42    = STOF(ISTOF + 42)
      RT_43    = STOF(ISTOF + 43)
      RT_44    = STOF(ISTOF + 44)
      RT_45    = STOF(ISTOF + 45)
      RT_46    = STOF(ISTOF + 46)
      RT_47    = STOF(ISTOF + 47)
      RT_48    = STOF(ISTOF + 48)
      RT_49    = STOF(ISTOF + 49)
      RT_50    = STOF(ISTOF + 50)
      RT_51    = STOF(ISTOF + 51)
      RT_52    = STOF(ISTOF + 52)
      RT_53    = STOF(ISTOF + 53)
      RT_54    = STOF(ISTOF + 54)
      RT_55    = STOF(ISTOF + 55)
      RT_56    = STOF(ISTOF + 56)
      RT_57    = STOF(ISTOF + 57)
      RT_58    = STOF(ISTOF + 58)
      RT_59    = STOF(ISTOF + 59)
      RT_60    = STOF(ISTOF + 60)
      RT_61    = STOF(ISTOF + 61)
      RT_62    = STOF(ISTOF + 62)
      RT_63    = STOF(ISTOF + 63)
      RT_64    = STOF(ISTOF + 64)
      RT_65    = STOF(ISTOF + 65)
      RT_66    = STOF(ISTOF + 66)
      RT_67    = STOF(ISTOF + 67)
      RT_68    = STOF(ISTOF + 68)
      RT_69    = STOF(ISTOF + 69)
      RT_70    = STOF(ISTOF + 70)
      RT_71    = STOF(ISTOF + 71)
      RT_72    = STOF(ISTOF + 72)
      RT_73    = STOF(ISTOF + 73)
      RT_74    = STOF(ISTOF + 74)
      RT_75    = STOF(ISTOF + 75)
      RT_76    = STOF(ISTOF + 76)
      RT_77    = STOF(ISTOF + 77)
      RT_78    = STOF(ISTOF + 78)
      RT_79    = STOF(ISTOF + 79)
      RT_80    = STOF(ISTOF + 80)
      RT_81    = STOF(ISTOF + 81)
      RT_82    = STOF(ISTOF + 82)
      RT_83    = STOF(ISTOF + 83)
      RT_84    = STOF(ISTOF + 84)
      RT_85    = STOF(ISTOF + 85)
      RT_86    = STOF(ISTOF + 86)
      RT_87    = STOF(ISTOF + 87)
      RT_88    = STOF(ISTOF + 88)
      RT_89    = STOF(ISTOF + 89)
      RT_90    = STOF(ISTOF + 90)
      RT_91    = STOF(ISTOF + 91)
      RT_92    = STOF(ISTOF + 92)
      RT_93    = STOF(ISTOF + 93)
      RT_94    = STOF(ISTOF + 94)
      RT_95    = STOF(ISTOF + 95)
      RT_96    = STOF(ISTOF + 96)
      RT_97    = STOF(ISTOF + 97)
      RT_98    = STOF(ISTOF + 98)
      RT_99    = STOF(ISTOF + 99)
      RT_100   = STOF(ISTOF + 100)
      RT_101   = STOF(ISTOF + 101)
      RT_102   = STOF(ISTOF + 102)
      RT_103   = STOF(ISTOF + 103)
      RT_104   = STOF(ISTOF + 104)
      RT_105   = STOF(ISTOF + 105)
      RT_106   = STOF(ISTOF + 106)
      RT_107   = STOF(ISTOF + 107)
      RT_108   = STOF(ISTOF + 108)
      RT_109   = STOF(ISTOF + 109)
      RT_110   = STOF(ISTOF + 110)
      RT_111   = STOF(ISTOF + 111)
      RT_112   = STOF(ISTOF + 112)
      RT_113   = STOF(ISTOF + 113)
      RT_114   = STOF(ISTOF + 114)
      RT_115   = STOF(ISTOF + 115)
      RT_116   = STOF(ISTOF + 116)
      RT_117   = STOF(ISTOF + 117)
      RT_118   = STOF(ISTOF + 118)
      RT_119   = STOF(ISTOF + 119)
      RT_120   = STOF(ISTOF + 120)
      RT_121   = STOF(ISTOF + 121)
      RT_122   = STOF(ISTOF + 122)
      RT_123   = STOF(ISTOF + 123)
      RT_124   = STOF(ISTOF + 124)
      RT_125   = STOF(ISTOF + 125)
      RT_126   = STOF(ISTOF + 126)
      RT_127   = STOF(ISTOF + 127)
      RT_128   = STOF(ISTOF + 128)
      RT_129   = STOF(ISTOF + 129)
      RT_130   = STOF(ISTOF + 130)
      RT_131   = STOF(ISTOF + 131)
      RT_132   = STOF(ISTOF + 132)
      RT_133   = STOF(ISTOF + 133)
      RT_134   = STOF(ISTOF + 134)
      RT_135   = STOF(ISTOF + 135)
      RT_136   = STOF(ISTOF + 136)
      RT_137   = STOF(ISTOF + 137)
      RT_138   = STOF(ISTOF + 138)
      RT_139   = STOF(ISTOF + 139)
      RT_140   = STOF(ISTOF + 140)
      RT_141   = STOF(ISTOF + 141)
      RT_142   = STOF(ISTOF + 142)
      RT_143   = STOF(ISTOF + 143)
      RT_144   = STOF(ISTOF + 144)
      RT_145   = STOF(ISTOF + 145)
      RT_146   = STOF(ISTOF + 146)
      RT_147   = STOF(ISTOF + 147)
      RT_148   = STOF(ISTOF + 148)
      RT_149   = STOF(ISTOF + 149)
      RT_150   = STOF(ISTOF + 150)
      RT_151   = STOF(ISTOF + 151)
      RT_152   = STOF(ISTOF + 152)
      RT_153   = STOF(ISTOF + 153)
      RT_154   = STOF(ISTOF + 154)
      RT_155   = STOF(ISTOF + 155)
      RT_156   = STOF(ISTOF + 156)
      RT_157   = STOF(ISTOF + 157)
      RT_158   = STOF(ISTOF + 158)
      RT_159   = STOF(ISTOF + 159)
      RT_160   = STOF(ISTOF + 160)
      RT_161   = STOF(ISTOF + 161)
      RT_162   = STOF(ISTOF + 162)
      RT_163   = STOF(ISTOF + 163)
      RT_164   = STOF(ISTOF + 164)
      RT_165   = STOF(ISTOF + 165)
      RT_166   = STOF(ISTOF + 166)
      RT_167   = STOF(ISTOF + 167)
      RT_168   = STOF(ISTOF + 168)
      RT_169   = STOF(ISTOF + 169)
      RT_170   = STOF(ISTOF + 170)
      RT_171   = STOF(ISTOF + 171)
      RT_172   = STOF(ISTOF + 172)
      RT_173   = STOF(ISTOF + 173)
      RT_174   = STOF(ISTOF + 174)
      RT_175   = STOF(ISTOF + 175)
      RT_176   = STOF(ISTOF + 176)
      RT_177   = STOF(ISTOF + 177)
      RT_178   = STOF(ISTOF + 178)
      RT_179   = STOF(ISTOF + 179)
      RT_180   = STOF(ISTOF + 180)
      RT_181   = STOF(ISTOF + 181)
      RT_182   = STOF(ISTOF + 182)
      RT_183   = STOF(ISTOF + 183)
      RT_184   = STOF(ISTOF + 184)
      RT_185   = STOF(ISTOF + 185)
      RT_186   = STOF(ISTOF + 186)
      RT_187   = STOF(ISTOF + 187)
      RT_188   = STOF(ISTOF + 188)
      RT_189   = STOF(ISTOF + 189)
      RT_190   = STOF(ISTOF + 190)
      RT_191   = STOF(ISTOF + 191)
      RT_192   = STOF(ISTOF + 192)
      RT_193   = STOF(ISTOF + 193)
      RT_194   = STOF(ISTOF + 194)
      RT_195   = STOF(ISTOF + 195)
      RT_196   = STOF(ISTOF + 196)
      RT_197   = STOF(ISTOF + 197)
      RT_198   = STOF(ISTOF + 198)
      RT_199   = STOF(ISTOF + 199)
      RT_200   = STOF(ISTOF + 200)
      RT_201   = STOF(ISTOF + 201)
      RT_202   = STOF(ISTOF + 202)
      RT_203   = STOF(ISTOF + 203)
      RT_204   = STOF(ISTOF + 204)
      RT_205   = STOF(ISTOF + 205)
      RT_206   = STOF(ISTOF + 206)
      RT_207   = STOF(ISTOF + 207)
      RT_208   = STOF(ISTOF + 208)
      RT_209   = STOF(ISTOF + 209)
      RT_210   = STOF(ISTOF + 210)
      RT_211   = STOF(ISTOF + 211)
      RT_212   = STOF(ISTOF + 212)
      RT_213   = STOF(ISTOF + 213)
      RT_214   = STOF(ISTOF + 214)
      RT_215   = STOF(ISTOF + 215)
      RT_216   = STOF(ISTOF + 216)
      RT_217   = STOF(ISTOF + 217)
      RT_218   = STOF(ISTOF + 218)
      RT_219   = STOF(ISTOF + 219)
      RT_220   = STOF(ISTOF + 220)
      RT_221   = STOF(ISTOF + 221)
      RT_222   = STOF(ISTOF + 222)
      RT_223   = STOF(ISTOF + 223)
      RT_224   = STOF(ISTOF + 224)
      RT_225   = STOF(ISTOF + 225)
      RT_226   = STOF(ISTOF + 226)
      RT_227   = STOF(ISTOF + 227)
      RT_228   = STOF(ISTOF + 228)
      RT_229   = STOF(ISTOF + 229)
      RT_230   = STOF(ISTOF + 230)
      RT_231   = STOF(ISTOF + 231)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[time-sig] Output of Simulation Time 
      RT_1 = TIME

! 20:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_1,0.0,0.0,1.0,RVD2_1)
      RT_2 = RVD2_1(1)

! 30:[gain] Gain Block 
!  Gain
      RT_3 = 3.0 * RT_2

! 40:[pgb] Output Channel 'Odp.skok.prop'

      PGB(IPGB+1) = RT_3

! 50:[time-sig] Output of Simulation Time 
      RT_28 = TIME

! 60:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_28,0.0,0.0,1.0,RVD2_1)
      RT_29 = RVD2_1(1)

! 70:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_25 = DERIV1(RVD1_1,RT_29)
!

! 80:[realpole] Real Pole 
!  Real_Pole
      RT_26 = REALPOLE(0,1,0,1.0,2.73,RT_25,0.0,-1.0E20,1.0E20)

! 90:[realpole] Real Pole 
!  Real_Pole
      RT_27 = REALPOLE(0,1,0,3.0,2.37,RT_26,0.0,-1.0E20,1.0E20)

! 100:[time-sig] Output of Simulation Time 
      RT_4 = TIME

! 110:[pgb] Output Channel 'RT_27'

      PGB(IPGB+2) = RT_27

! 120:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_4,0.0,0.0,1.0,RVD2_1)
      RT_5 = RVD2_1(1)

! 130:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_7 = DERIV1(RVD1_1,RT_5)
!

! 140:[gain] Gain Block 
!  Gain
      RT_6 = 3.0 * RT_7

! 150:[pgb] Output Channel 'Odp.imp.prop'

      PGB(IPGB+3) = RT_6

! 160:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_32 = DERIV1(RVD1_1,RT_29)
!

! 170:[realpole] Real Pole 
!  Real_Pole
      RT_30 = REALPOLE(0,1,0,1.0,2.73,RT_32,0.0,-1.0E20,1.0E20)

! 180:[realpole] Real Pole 
!  Real_Pole
      RT_31 = REALPOLE(0,1,0,6.0,2.37,RT_30,0.0,-1.0E20,1.0E20)

! 190:[pgb] Output Channel 'RT_31'

      PGB(IPGB+4) = RT_31

! 200:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_33 = DERIV1(RVD1_1,RT_29)
!

! 210:[realpole] Real Pole 
!  Real_Pole
      RT_34 = REALPOLE(0,1,0,1.0,2.73,RT_33,0.0,-1.0E20,1.0E20)

! 220:[realpole] Real Pole 
!  Real_Pole
      RT_35 = REALPOLE(0,1,0,9.0,2.37,RT_34,0.0,-1.0E20,1.0E20)

! 230:[pgb] Output Channel 'RT_35'

      PGB(IPGB+5) = RT_35

! 240:[time-sig] Output of Simulation Time 
      RT_157 = TIME

! 250:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_157,0.0,0.0,1.0,RVD2_1)
      RT_154 = RVD2_1(1)

! 260:[realpole] Real Pole 
!  Real_Pole
      RT_155 = REALPOLE(0,1,0,1.0,2.73,RT_154,0.0,-1.0E20,1.0E20)

! 270:[realpole] Real Pole 
!  Real_Pole
      RT_156 = REALPOLE(0,1,0,3.0,2.37,RT_155,0.0,-1.0E20,1.0E20)

! 280:[pgb] Output Channel 'RT_156'

      PGB(IPGB+6) = RT_156

! 290:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_36 = DERIV1(RVD1_1,RT_29)
!

! 300:[realpole] Real Pole 
!  Real_Pole
      RT_158 = REALPOLE(0,1,0,1.0,2.73,RT_154,0.0,-1.0E20,1.0E20)

! 310:[realpole] Real Pole 
!  Real_Pole
      RT_37 = REALPOLE(0,1,0,1.0,3.0,RT_36,0.0,-1.0E20,1.0E20)

! 320:[realpole] Real Pole 
!  Real_Pole
      RT_159 = REALPOLE(0,1,0,6.0,2.37,RT_158,0.0,-1.0E20,1.0E20)

! 330:[pgb] Output Channel 'RT_159'

      PGB(IPGB+7) = RT_159

! 340:[realpole] Real Pole 
!  Real_Pole
      RT_38 = REALPOLE(0,1,0,3.0,2.37,RT_37,0.0,-1.0E20,1.0E20)

! 350:[pgb] Output Channel 'RT_38'

      PGB(IPGB+8) = RT_38

! 360:[time-sig] Output of Simulation Time 
      RT_8 = TIME

! 370:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_8,0.0,0.0,1.0,RVD2_1)
      RT_9 = RVD2_1(1)

! 380:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_9
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_10 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 390:[pgb] Output Channel 'odp.skok.calk.ideal'

      PGB(IPGB+9) = RT_10

! 400:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_39 = DERIV1(RVD1_1,RT_29)
!

! 410:[realpole] Real Pole 
!  Real_Pole
      RT_40 = REALPOLE(0,1,0,1.0,6.0,RT_39,0.0,-1.0E20,1.0E20)

! 420:[realpole] Real Pole 
!  Real_Pole
      RT_41 = REALPOLE(0,1,0,3.0,2.37,RT_40,0.0,-1.0E20,1.0E20)

! 430:[pgb] Output Channel 'RT_41'

      PGB(IPGB+10) = RT_41

! 440:[realpole] Real Pole 
!  Real_Pole
      RT_160 = REALPOLE(0,1,0,1.0,2.73,RT_154,0.0,-1.0E20,1.0E20)

! 450:[realpole] Real Pole 
!  Real_Pole
      RT_161 = REALPOLE(0,1,0,9.0,2.37,RT_160,0.0,-1.0E20,1.0E20)

! 460:[pgb] Output Channel 'RT_161'

      PGB(IPGB+11) = RT_161

! 470:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_42 = DERIV1(RVD1_1,RT_29)
!

! 480:[realpole] Real Pole 
!  Real_Pole
      RT_43 = REALPOLE(0,1,0,1.0,9.0,RT_42,0.0,-1.0E20,1.0E20)

! 490:[realpole] Real Pole 
!  Real_Pole
      RT_44 = REALPOLE(0,1,0,3.0,2.37,RT_43,0.0,-1.0E20,1.0E20)

! 500:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_9
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_11 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 510:[pgb] Output Channel 'RT_44'

      PGB(IPGB+12) = RT_44

! 520:[realpole] Real Pole 
!  Real_Pole
      RT_12 = REALPOLE(0,1,0,3.0,2.37,RT_11,0.0,-1.0E20,1.0E20)

! 530:[pgb] Output Channel 'odp.skok.calk.rzecz'

      PGB(IPGB+13) = RT_12

! 540:[realpole] Real Pole 
!  Real_Pole
      RT_162 = REALPOLE(0,1,0,1.0,3.0,RT_154,0.0,-1.0E20,1.0E20)

! 550:[realpole] Real Pole 
!  Real_Pole
      RT_163 = REALPOLE(0,1,0,3.0,2.37,RT_162,0.0,-1.0E20,1.0E20)

! 560:[pgb] Output Channel 'RT_163'

      PGB(IPGB+14) = RT_163

! 570:[realpole] Real Pole 
!  Real_Pole
      RT_164 = REALPOLE(0,1,0,1.0,6.0,RT_154,0.0,-1.0E20,1.0E20)

! 580:[realpole] Real Pole 
!  Real_Pole
      RT_165 = REALPOLE(0,1,0,3.0,2.37,RT_164,0.0,-1.0E20,1.0E20)

! 590:[pgb] Output Channel 'RT_165'

      PGB(IPGB+15) = RT_165

! 600:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_13 = DERIV1(RVD1_1,RT_9)
!

! 610:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_13
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_15 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 620:[pgb] Output Channel 'odp.imp.calk.ideal'

      PGB(IPGB+16) = RT_15

! 630:[realpole] Real Pole 
!  Real_Pole
      RT_166 = REALPOLE(0,1,0,1.0,9.0,RT_154,0.0,-1.0E20,1.0E20)

! 640:[realpole] Real Pole 
!  Real_Pole
      RT_167 = REALPOLE(0,1,0,3.0,2.37,RT_166,0.0,-1.0E20,1.0E20)

! 650:[pgb] Output Channel 'RT_167'

      PGB(IPGB+17) = RT_167

! 660:[time-sig] Output of Simulation Time 
      RT_57 = TIME

! 670:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_57,0.0,0.0,1.0,RVD2_1)
      RT_58 = RVD2_1(1)

! 680:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_60 = DERIV1(RVD1_1,RT_58)
!

! 690:[gain] Gain Block 
!  Gain
      RT_59 = 3.0 * RT_60

! 700:[pgb] Output Channel 'k=3'

      PGB(IPGB+18) = RT_59

! 710:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_14 = DERIV1(RVD1_1,RT_9)
!

! 720:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_14
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_16 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 730:[realpole] Real Pole 
!  Real_Pole
      RT_17 = REALPOLE(0,1,0,3.0,2.37,RT_16,0.0,-1.0E20,1.0E20)

! 740:[pgb] Output Channel 'odp.imp.calk.rzecz'

      PGB(IPGB+19) = RT_17

! 750:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_62 = DERIV1(RVD1_1,RT_58)
!

! 760:[gain] Gain Block 
!  Gain
      RT_61 = 6.0 * RT_62

! 770:[pgb] Output Channel 'k=6'

      PGB(IPGB+20) = RT_61

! 780:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_64 = DERIV1(RVD1_1,RT_58)
!

! 790:[gain] Gain Block 
!  Gain
      RT_63 = 9.0 * RT_64

! 800:[pgb] Output Channel 'k=9'

      PGB(IPGB+21) = RT_63

! 810:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_18 = DERIV1(RVD1_1,RT_9)
!

! 820:[pgb] Output Channel 'odp.skok.roz.ideal'

      PGB(IPGB+22) = RT_18

! 830:[time-sig] Output of Simulation Time 
      RT_168 = TIME

! 840:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_168,0.0,0.0,1.0,RVD2_1)
      RT_169 = RVD2_1(1)

! 850:[gain] Gain Block 
!  Gain
      RT_170 = 3.0 * RT_169

! 860:[pgb] Output Channel 'k=3'

      PGB(IPGB+23) = RT_170

! 870:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_19 = DERIV1(RVD1_1,RT_9)
!

! 880:[realpole] Real Pole 
!  Real_Pole
      RT_20 = REALPOLE(0,1,0,3.0,2.37,RT_19,0.0,-1.0E20,1.0E20)

! 890:[pgb] Output Channel 'odp.skok.roz.ideal'

      PGB(IPGB+24) = RT_20

! 900:[gain] Gain Block 
!  Gain
      RT_171 = 6.0 * RT_169

! 910:[pgb] Output Channel 'k=6'

      PGB(IPGB+25) = RT_171

! 920:[time-sig] Output of Simulation Time 
      RT_65 = TIME

! 930:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_65,0.0,0.0,1.0,RVD2_1)
      RT_66 = RVD2_1(1)

! 940:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_72 = DERIV1(RVD1_1,RT_66)
!

! 950:[gain] Gain Block 
!  Gain
      RT_67 = 3.0 * RT_72

! 960:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_67
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_68 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 970:[pgb] Output Channel 'k=3'

      PGB(IPGB+26) = RT_68

! 980:[gain] Gain Block 
!  Gain
      RT_172 = 9.0 * RT_169

! 990:[pgb] Output Channel 'k=9'

      PGB(IPGB+27) = RT_172

! 1000:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_74 = DERIV1(RVD1_1,RT_66)
!

! 1010:[gain] Gain Block 
!  Gain
      RT_73 = 6.0 * RT_74

! 1020:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_73
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_75 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 1030:[pgb] Output Channel 'k=6'

      PGB(IPGB+28) = RT_75

! 1040:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_77 = DERIV1(RVD1_1,RT_66)
!

! 1050:[gain] Gain Block 
!  Gain
      RT_76 = 9.0 * RT_77

! 1060:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_76
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_78 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 1070:[pgb] Output Channel 'k=9'

      PGB(IPGB+29) = RT_78

! 1080:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_45 = DERIV1(RVD1_1,RT_9)
!

! 1090:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_46 = DERIV1(RVD1_1,RT_45)
!

! 1100:[pgb] Output Channel 'odp.imp.roz.ideal'

      PGB(IPGB+30) = RT_46

! 1110:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_82 = DERIV1(RVD1_1,RT_66)
!

! 1120:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_82
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_83 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 1130:[realpole] Real Pole 
!  Real_Pole
      RT_84 = REALPOLE(0,1,0,3.0,2.37,RT_83,0.0,-1.0E20,1.0E20)

! 1140:[pgb] Output Channel 'k=3'

      PGB(IPGB+31) = RT_84

! 1150:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_47 = DERIV1(RVD1_1,RT_9)
!

! 1160:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_48 = DERIV1(RVD1_1,RT_47)
!

! 1170:[realpole] Real Pole 
!  Real_Pole
      RT_49 = REALPOLE(0,1,0,3.0,2.37,RT_48,0.0,-1.0E20,1.0E20)

! 1180:[pgb] Output Channel 'odp.imp.roz.ideal'

      PGB(IPGB+32) = RT_49

! 1190:[time-sig] Output of Simulation Time 
      RT_173 = TIME

! 1200:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_173,0.0,0.0,1.0,RVD2_1)
      RT_174 = RVD2_1(1)

! 1210:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_79 = DERIV1(RVD1_1,RT_66)
!

! 1220:[gain] Gain Block 
!  Gain
      RT_175 = 3.0 * RT_174

! 1230:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_79
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_80 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 1240:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_175
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_176 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD&
     &2_2, RVD2_1)

! 1250:[pgb] Output Channel 'k=3'

      PGB(IPGB+33) = RT_176

! 1260:[realpole] Real Pole 
!  Real_Pole
      RT_81 = REALPOLE(0,1,0,6.0,2.37,RT_80,0.0,-1.0E20,1.0E20)

! 1270:[pgb] Output Channel 'k=6'

      PGB(IPGB+34) = RT_81

! 1280:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_69 = DERIV1(RVD1_1,RT_66)
!

! 1290:[gain] Gain Block 
!  Gain
      RT_179 = 6.0 * RT_174

! 1300:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_69
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_70 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 1310:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_179
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_180 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD&
     &2_2, RVD2_1)

! 1320:[pgb] Output Channel 'k=6'

      PGB(IPGB+35) = RT_180

! 1330:[realpole] Real Pole 
!  Real_Pole
      RT_71 = REALPOLE(0,1,0,9.0,2.37,RT_70,0.0,-1.0E20,1.0E20)

! 1340:[pgb] Output Channel 'k=9'

      PGB(IPGB+36) = RT_71

! 1350:[gain] Gain Block 
!  Gain
      RT_181 = 9.0 * RT_174

! 1360:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_181
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_182 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD&
     &2_2, RVD2_1)

! 1370:[pgb] Output Channel 'k=9'

      PGB(IPGB+37) = RT_182

! 1380:[realpole] Real Pole 
!  Real_Pole
      RT_21 = REALPOLE(0,1,0,3.0,2.37,RT_9,0.0,-1.0E20,1.0E20)

! 1390:[pgb] Output Channel 'odp.skok.inercyjnego I rzedu'

      PGB(IPGB+38) = RT_21

! 1400:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_174
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_185 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD&
     &2_2, RVD2_1)

! 1410:[realpole] Real Pole 
!  Real_Pole
      RT_186 = REALPOLE(0,1,0,3.0,2.37,RT_185,0.0,-1.0E20,1.0E20)

! 1420:[pgb] Output Channel 'k=3'

      PGB(IPGB+39) = RT_186

! 1430:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_174
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_183 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD&
     &2_2, RVD2_1)

! 1440:[realpole] Real Pole 
!  Real_Pole
      RT_184 = REALPOLE(0,1,0,6.0,2.37,RT_183,0.0,-1.0E20,1.0E20)

! 1450:[pgb] Output Channel 'k=6'

      PGB(IPGB+40) = RT_184

! 1460:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_174
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_177 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD&
     &2_2, RVD2_1)

! 1470:[realpole] Real Pole 
!  Real_Pole
      RT_178 = REALPOLE(0,1,0,9.0,2.37,RT_177,0.0,-1.0E20,1.0E20)

! 1480:[pgb] Output Channel 'k=9'

      PGB(IPGB+41) = RT_178

! 1490:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_50 = DERIV1(RVD1_1,RT_9)
!

! 1500:[realpole] Real Pole 
!  Real_Pole
      RT_51 = REALPOLE(0,1,0,3.0,2.37,RT_50,0.0,-1.0E20,1.0E20)

! 1510:[pgb] Output Channel 'odp.skok.inercyjnego I rzedu'

      PGB(IPGB+42) = RT_51

! 1520:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_91 = DERIV1(RVD1_1,RT_66)
!

! 1530:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_91
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_92 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 1540:[realpole] Real Pole 
!  Real_Pole
      RT_93 = REALPOLE(0,1,0,3.0,3.0,RT_92,0.0,-1.0E20,1.0E20)

! 1550:[pgb] Output Channel 'T=3'

      PGB(IPGB+43) = RT_93

! 1560:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_88 = DERIV1(RVD1_1,RT_66)
!

! 1570:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_88
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_89 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 1580:[realpole] Real Pole 
!  Real_Pole
      RT_90 = REALPOLE(0,1,0,3.0,6.0,RT_89,0.0,-1.0E20,1.0E20)

! 1590:[pgb] Output Channel 'T=6'

      PGB(IPGB+44) = RT_90

! 1600:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_85 = DERIV1(RVD1_1,RT_66)
!

! 1610:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_85
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_86 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD2&
     &_2, RVD2_1)

! 1620:[realpole] Real Pole 
!  Real_Pole
      RT_22 = REALPOLE(0,1,0,1.0,2.73,RT_9,0.0,-1.0E20,1.0E20)

! 1630:[realpole] Real Pole 
!  Real_Pole
      RT_87 = REALPOLE(0,1,0,3.0,9.0,RT_86,0.0,-1.0E20,1.0E20)

! 1640:[realpole] Real Pole 
!  Real_Pole
      RT_23 = REALPOLE(0,1,0,3.0,2.37,RT_22,0.0,-1.0E20,1.0E20)

! 1650:[pgb] Output Channel 'T=9'

      PGB(IPGB+45) = RT_87

! 1660:[pgb] Output Channel 'odp.skok.inercyjnego II rzedu'

      PGB(IPGB+46) = RT_23

! 1670:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_174
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_191 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD&
     &2_2, RVD2_1)

! 1680:[realpole] Real Pole 
!  Real_Pole
      RT_192 = REALPOLE(0,1,0,3.0,3.0,RT_191,0.0,-1.0E20,1.0E20)

! 1690:[pgb] Output Channel 'T=3'

      PGB(IPGB+47) = RT_192

! 1700:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_174
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_189 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD&
     &2_2, RVD2_1)

! 1710:[realpole] Real Pole 
!  Real_Pole
      RT_190 = REALPOLE(0,1,0,3.0,6.0,RT_189,0.0,-1.0E20,1.0E20)

! 1720:[pgb] Output Channel 'T=6'

      PGB(IPGB+48) = RT_190

! 1730:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_52 = DERIV1(RVD1_1,RT_9)
!

! 1740:[realpole] Real Pole 
!  Real_Pole
      RT_53 = REALPOLE(0,1,0,1.0,2.73,RT_52,0.0,-1.0E20,1.0E20)

! 1750:[realpole] Real Pole 
!  Real_Pole
      RT_54 = REALPOLE(0,1,0,3.0,2.37,RT_53,0.0,-1.0E20,1.0E20)

! 1760:[pgb] Output Channel 'odp.imp.inercyjnego II rzedu'

      PGB(IPGB+49) = RT_54

! 1770:[time-sig] Output of Simulation Time 
      RT_94 = TIME

! 1780:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_94,0.0,0.0,1.0,RVD2_1)
      RT_95 = RVD2_1(1)

! 1790:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_174
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_187 = EMTDC_XINT(0, 0, 0, RVD1_1, 2.73, 0.0, -100.0, 100.0, RVD&
     &2_2, RVD2_1)

! 1800:[realpole] Real Pole 
!  Real_Pole
      RT_188 = REALPOLE(0,1,0,3.0,9.0,RT_187,0.0,-1.0E20,1.0E20)

! 1810:[pgb] Output Channel 'T=9'

      PGB(IPGB+50) = RT_188

! 1820:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_104 = DERIV1(RVD1_1,RT_95)
!

! 1830:[gain] Gain Block 
!  Gain
      RT_96 = 3.0 * RT_104

! 1840:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_97 = DERIV1(RVD1_1,RT_96)
!

! 1850:[pgb] Output Channel 'k=3'

      PGB(IPGB+51) = RT_97

! 1860:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_107 = DERIV1(RVD1_1,RT_95)
!

! 1870:[gain] Gain Block 
!  Gain
      RT_105 = 6.0 * RT_107

! 1880:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_106 = DERIV1(RVD1_1,RT_105)
!

! 1890:[pgb] Output Channel 'k=6'

      PGB(IPGB+52) = RT_106

! 1900:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_110 = DERIV1(RVD1_1,RT_95)
!

! 1910:[gain] Gain Block 
!  Gain
      RT_108 = 9.0 * RT_110

! 1920:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_109 = DERIV1(RVD1_1,RT_108)
!

! 1930:[pgb] Output Channel 'k=9'

      PGB(IPGB+53) = RT_109

! 1940:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_98 = DERIV1(RVD1_1,RT_95)
!

! 1950:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_99 = DERIV1(RVD1_1,RT_98)
!

! 1960:[realpole] Real Pole 
!  Real_Pole
      RT_100 = REALPOLE(0,1,0,3.0,2.37,RT_99,0.0,-1.0E20,1.0E20)

! 1970:[pgb] Output Channel 'k=3'

      PGB(IPGB+54) = RT_100

! 1980:[time-sig] Output of Simulation Time 
      RT_193 = TIME

! 1990:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_193,0.0,0.0,1.0,RVD2_1)
      RT_194 = RVD2_1(1)

! 2000:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_9,RT_24)

! 2010:[pgb] Output Channel 'odp.skok.opoz'

      PGB(IPGB+55) = RT_24

! 2020:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_111 = DERIV1(RVD1_1,RT_95)
!

! 2030:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_112 = DERIV1(RVD1_1,RT_111)
!

! 2040:[realpole] Real Pole 
!  Real_Pole
      RT_113 = REALPOLE(0,1,0,6.0,2.37,RT_112,0.0,-1.0E20,1.0E20)

! 2050:[pgb] Output Channel 'k=6'

      PGB(IPGB+56) = RT_113

! 2060:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_114 = DERIV1(RVD1_1,RT_95)
!

! 2070:[gain] Gain Block 
!  Gain
      RT_195 = 3.0 * RT_194

! 2080:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_115 = DERIV1(RVD1_1,RT_114)
!

! 2090:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_196 = DERIV1(RVD1_1,RT_195)
!

! 2100:[pgb] Output Channel 'k=3'

      PGB(IPGB+57) = RT_196

! 2110:[realpole] Real Pole 
!  Real_Pole
      RT_116 = REALPOLE(0,1,0,9.0,2.37,RT_115,0.0,-1.0E20,1.0E20)

! 2120:[pgb] Output Channel 'k=9'

      PGB(IPGB+58) = RT_116

! 2130:[gain] Gain Block 
!  Gain
      RT_201 = 6.0 * RT_194

! 2140:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_202 = DERIV1(RVD1_1,RT_201)
!

! 2150:[pgb] Output Channel 'k=6'

      PGB(IPGB+59) = RT_202

! 2160:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_55 = DERIV1(RVD1_1,RT_9)
!

! 2170:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_55,RT_56)

! 2180:[pgb] Output Channel 'odp.skok.opoz'

      PGB(IPGB+60) = RT_56

! 2190:[gain] Gain Block 
!  Gain
      RT_203 = 9.0 * RT_194

! 2200:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_204 = DERIV1(RVD1_1,RT_203)
!

! 2210:[pgb] Output Channel 'k=9'

      PGB(IPGB+61) = RT_204

! 2220:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_197 = DERIV1(RVD1_1,RT_194)
!

! 2230:[realpole] Real Pole 
!  Real_Pole
      RT_198 = REALPOLE(0,1,0,3.0,2.37,RT_197,0.0,-1.0E20,1.0E20)

! 2240:[pgb] Output Channel 'k=3'

      PGB(IPGB+62) = RT_198

! 2250:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_205 = DERIV1(RVD1_1,RT_194)
!

! 2260:[realpole] Real Pole 
!  Real_Pole
      RT_206 = REALPOLE(0,1,0,6.0,2.37,RT_205,0.0,-1.0E20,1.0E20)

! 2270:[pgb] Output Channel 'k=6'

      PGB(IPGB+63) = RT_206

! 2280:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_101 = DERIV1(RVD1_1,RT_95)
!

! 2290:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_207 = DERIV1(RVD1_1,RT_194)
!

! 2300:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_102 = DERIV1(RVD1_1,RT_101)
!

! 2310:[realpole] Real Pole 
!  Real_Pole
      RT_208 = REALPOLE(0,1,0,9.0,2.37,RT_207,0.0,-1.0E20,1.0E20)

! 2320:[pgb] Output Channel 'k=9'

      PGB(IPGB+64) = RT_208

! 2330:[realpole] Real Pole 
!  Real_Pole
      RT_103 = REALPOLE(0,1,0,3.0,3.0,RT_102,0.0,-1.0E20,1.0E20)

! 2340:[pgb] Output Channel 'T=3'

      PGB(IPGB+65) = RT_103

! 2350:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_117 = DERIV1(RVD1_1,RT_95)
!

! 2360:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_118 = DERIV1(RVD1_1,RT_117)
!

! 2370:[realpole] Real Pole 
!  Real_Pole
      RT_119 = REALPOLE(0,1,0,3.0,6.0,RT_118,0.0,-1.0E20,1.0E20)

! 2380:[pgb] Output Channel 'T=6'

      PGB(IPGB+66) = RT_119

! 2390:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_120 = DERIV1(RVD1_1,RT_95)
!

! 2400:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_121 = DERIV1(RVD1_1,RT_120)
!

! 2410:[realpole] Real Pole 
!  Real_Pole
      RT_122 = REALPOLE(0,1,0,3.0,9.0,RT_121,0.0,-1.0E20,1.0E20)

! 2420:[pgb] Output Channel 'T=9'

      PGB(IPGB+67) = RT_122

! 2430:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_199 = DERIV1(RVD1_1,RT_194)
!

! 2440:[realpole] Real Pole 
!  Real_Pole
      RT_200 = REALPOLE(0,1,0,3.0,3.0,RT_199,0.0,-1.0E20,1.0E20)

! 2450:[pgb] Output Channel 'T=3'

      PGB(IPGB+68) = RT_200

! 2460:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_209 = DERIV1(RVD1_1,RT_194)
!

! 2470:[realpole] Real Pole 
!  Real_Pole
      RT_210 = REALPOLE(0,1,0,3.0,6.0,RT_209,0.0,-1.0E20,1.0E20)

! 2480:[pgb] Output Channel 'T=6'

      PGB(IPGB+69) = RT_210

! 2490:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_211 = DERIV1(RVD1_1,RT_194)
!

! 2500:[realpole] Real Pole 
!  Real_Pole
      RT_212 = REALPOLE(0,1,0,3.0,9.0,RT_211,0.0,-1.0E20,1.0E20)

! 2510:[pgb] Output Channel 'T=9'

      PGB(IPGB+70) = RT_212

! 2520:[time-sig] Output of Simulation Time 
      RT_123 = TIME

! 2530:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_123,0.0,0.0,1.0,RVD2_1)
      RT_124 = RVD2_1(1)

! 2540:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_125 = DERIV1(RVD1_1,RT_124)
!

! 2550:[realpole] Real Pole 
!  Real_Pole
      RT_126 = REALPOLE(0,1,0,3.0,2.37,RT_125,0.0,-1.0E20,1.0E20)

! 2560:[pgb] Output Channel 'k=3'

      PGB(IPGB+71) = RT_126

! 2570:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_128 = DERIV1(RVD1_1,RT_124)
!

! 2580:[realpole] Real Pole 
!  Real_Pole
      RT_127 = REALPOLE(0,1,0,6.0,2.37,RT_128,0.0,-1.0E20,1.0E20)

! 2590:[pgb] Output Channel 'k=6'

      PGB(IPGB+72) = RT_127

! 2600:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_130 = DERIV1(RVD1_1,RT_124)
!

! 2610:[realpole] Real Pole 
!  Real_Pole
      RT_129 = REALPOLE(0,1,0,9.0,2.37,RT_130,0.0,-1.0E20,1.0E20)

! 2620:[pgb] Output Channel 'k=9'

      PGB(IPGB+73) = RT_129

! 2630:[time-sig] Output of Simulation Time 
      RT_213 = TIME

! 2640:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_213,0.0,0.0,1.0,RVD2_1)
      RT_214 = RVD2_1(1)

! 2650:[realpole] Real Pole 
!  Real_Pole
      RT_215 = REALPOLE(0,1,0,3.0,2.37,RT_214,0.0,-1.0E20,1.0E20)

! 2660:[pgb] Output Channel 'k=3'

      PGB(IPGB+74) = RT_215

! 2670:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_131 = DERIV1(RVD1_1,RT_124)
!

! 2680:[realpole] Real Pole 
!  Real_Pole
      RT_132 = REALPOLE(0,1,0,3.0,3.0,RT_131,0.0,-1.0E20,1.0E20)

! 2690:[pgb] Output Channel 'T=3'

      PGB(IPGB+75) = RT_132

! 2700:[realpole] Real Pole 
!  Real_Pole
      RT_216 = REALPOLE(0,1,0,6.0,2.37,RT_214,0.0,-1.0E20,1.0E20)

! 2710:[pgb] Output Channel 'k=6'

      PGB(IPGB+76) = RT_216

! 2720:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_134 = DERIV1(RVD1_1,RT_124)
!

! 2730:[realpole] Real Pole 
!  Real_Pole
      RT_133 = REALPOLE(0,1,0,3.0,6.0,RT_134,0.0,-1.0E20,1.0E20)

! 2740:[pgb] Output Channel 'T=6'

      PGB(IPGB+77) = RT_133

! 2750:[realpole] Real Pole 
!  Real_Pole
      RT_217 = REALPOLE(0,1,0,9.0,2.37,RT_214,0.0,-1.0E20,1.0E20)

! 2760:[pgb] Output Channel 'k=9'

      PGB(IPGB+78) = RT_217

! 2770:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_136 = DERIV1(RVD1_1,RT_124)
!

! 2780:[realpole] Real Pole 
!  Real_Pole
      RT_135 = REALPOLE(0,1,0,3.0,9.0,RT_136,0.0,-1.0E20,1.0E20)

! 2790:[pgb] Output Channel 'T=9'

      PGB(IPGB+79) = RT_135

! 2800:[realpole] Real Pole 
!  Real_Pole
      RT_218 = REALPOLE(0,1,0,3.0,3.0,RT_214,0.0,-1.0E20,1.0E20)

! 2810:[pgb] Output Channel 'T=3'

      PGB(IPGB+80) = RT_218

! 2820:[realpole] Real Pole 
!  Real_Pole
      RT_219 = REALPOLE(0,1,0,3.0,6.0,RT_214,0.0,-1.0E20,1.0E20)

! 2830:[pgb] Output Channel 'T=6'

      PGB(IPGB+81) = RT_219

! 2840:[realpole] Real Pole 
!  Real_Pole
      RT_220 = REALPOLE(0,1,0,3.0,9.0,RT_214,0.0,-1.0E20,1.0E20)

! 2850:[pgb] Output Channel 'T=9'

      PGB(IPGB+82) = RT_220

! 2860:[time-sig] Output of Simulation Time 
      RT_137 = TIME

! 2870:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_137,0.0,0.0,1.0,RVD2_1)
      RT_138 = RVD2_1(1)

! 2880:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_151 = DERIV1(RVD1_1,RT_138)
!

! 2890:[gain] Gain Block 
!  Gain
      RT_140 = 3.0 * RT_151

! 2900:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_140,RT_139)

! 2910:[pgb] Output Channel 'k=3'

      PGB(IPGB+83) = RT_139

! 2920:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_152 = DERIV1(RVD1_1,RT_138)
!

! 2930:[gain] Gain Block 
!  Gain
      RT_142 = 6.0 * RT_152

! 2940:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_142,RT_141)

! 2950:[pgb] Output Channel 'k=6'

      PGB(IPGB+84) = RT_141

! 2960:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_153 = DERIV1(RVD1_1,RT_138)
!

! 2970:[gain] Gain Block 
!  Gain
      RT_144 = 9.0 * RT_153

! 2980:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_144,RT_143)

! 2990:[pgb] Output Channel 'k=9'

      PGB(IPGB+85) = RT_143

! 3000:[time-sig] Output of Simulation Time 
      RT_221 = TIME

! 3010:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_221,0.0,0.0,1.0,RVD2_1)
      RT_222 = RVD2_1(1)

! 3020:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_146 = DERIV1(RVD1_1,RT_138)
!

! 3030:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_146,RT_145)

! 3040:[pgb] Output Channel 'T=3'

      PGB(IPGB+86) = RT_145

! 3050:[gain] Gain Block 
!  Gain
      RT_224 = 3.0 * RT_222

! 3060:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_224,RT_223)

! 3070:[pgb] Output Channel 'k=3'

      PGB(IPGB+87) = RT_223

! 3080:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_148 = DERIV1(RVD1_1,RT_138)
!

! 3090:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_148,RT_147)

! 3100:[pgb] Output Channel 'T=6'

      PGB(IPGB+88) = RT_147

! 3110:[gain] Gain Block 
!  Gain
      RT_226 = 6.0 * RT_222

! 3120:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_226,RT_225)

! 3130:[pgb] Output Channel 'k=6'

      PGB(IPGB+89) = RT_225

! 3140:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_150 = DERIV1(RVD1_1,RT_138)
!

! 3150:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_150,RT_149)

! 3160:[pgb] Output Channel 'T=9'

      PGB(IPGB+90) = RT_149

! 3170:[gain] Gain Block 
!  Gain
      RT_228 = 9.0 * RT_222

! 3180:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_228,RT_227)

! 3190:[pgb] Output Channel 'k=9'

      PGB(IPGB+91) = RT_227

! 3200:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_222,RT_229)

! 3210:[pgb] Output Channel 'T=3'

      PGB(IPGB+92) = RT_229

! 3220:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_222,RT_230)

! 3230:[pgb] Output Channel 'T=6'

      PGB(IPGB+93) = RT_230

! 3240:[tdelay] Delay Function 
      CALL DELAY2_EXE(RT_222,RT_231)

! 3250:[pgb] Output Channel 'T=9'

      PGB(IPGB+94) = RT_231

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 3) = RT_3
      STOF(ISTOF + 4) = RT_4
      STOF(ISTOF + 5) = RT_5
      STOF(ISTOF + 6) = RT_6
      STOF(ISTOF + 7) = RT_7
      STOF(ISTOF + 8) = RT_8
      STOF(ISTOF + 9) = RT_9
      STOF(ISTOF + 10) = RT_10
      STOF(ISTOF + 11) = RT_11
      STOF(ISTOF + 12) = RT_12
      STOF(ISTOF + 13) = RT_13
      STOF(ISTOF + 14) = RT_14
      STOF(ISTOF + 15) = RT_15
      STOF(ISTOF + 16) = RT_16
      STOF(ISTOF + 17) = RT_17
      STOF(ISTOF + 18) = RT_18
      STOF(ISTOF + 19) = RT_19
      STOF(ISTOF + 20) = RT_20
      STOF(ISTOF + 21) = RT_21
      STOF(ISTOF + 22) = RT_22
      STOF(ISTOF + 23) = RT_23
      STOF(ISTOF + 24) = RT_24
      STOF(ISTOF + 25) = RT_25
      STOF(ISTOF + 26) = RT_26
      STOF(ISTOF + 27) = RT_27
      STOF(ISTOF + 28) = RT_28
      STOF(ISTOF + 29) = RT_29
      STOF(ISTOF + 30) = RT_30
      STOF(ISTOF + 31) = RT_31
      STOF(ISTOF + 32) = RT_32
      STOF(ISTOF + 33) = RT_33
      STOF(ISTOF + 34) = RT_34
      STOF(ISTOF + 35) = RT_35
      STOF(ISTOF + 36) = RT_36
      STOF(ISTOF + 37) = RT_37
      STOF(ISTOF + 38) = RT_38
      STOF(ISTOF + 39) = RT_39
      STOF(ISTOF + 40) = RT_40
      STOF(ISTOF + 41) = RT_41
      STOF(ISTOF + 42) = RT_42
      STOF(ISTOF + 43) = RT_43
      STOF(ISTOF + 44) = RT_44
      STOF(ISTOF + 45) = RT_45
      STOF(ISTOF + 46) = RT_46
      STOF(ISTOF + 47) = RT_47
      STOF(ISTOF + 48) = RT_48
      STOF(ISTOF + 49) = RT_49
      STOF(ISTOF + 50) = RT_50
      STOF(ISTOF + 51) = RT_51
      STOF(ISTOF + 52) = RT_52
      STOF(ISTOF + 53) = RT_53
      STOF(ISTOF + 54) = RT_54
      STOF(ISTOF + 55) = RT_55
      STOF(ISTOF + 56) = RT_56
      STOF(ISTOF + 57) = RT_57
      STOF(ISTOF + 58) = RT_58
      STOF(ISTOF + 59) = RT_59
      STOF(ISTOF + 60) = RT_60
      STOF(ISTOF + 61) = RT_61
      STOF(ISTOF + 62) = RT_62
      STOF(ISTOF + 63) = RT_63
      STOF(ISTOF + 64) = RT_64
      STOF(ISTOF + 65) = RT_65
      STOF(ISTOF + 66) = RT_66
      STOF(ISTOF + 67) = RT_67
      STOF(ISTOF + 68) = RT_68
      STOF(ISTOF + 69) = RT_69
      STOF(ISTOF + 70) = RT_70
      STOF(ISTOF + 71) = RT_71
      STOF(ISTOF + 72) = RT_72
      STOF(ISTOF + 73) = RT_73
      STOF(ISTOF + 74) = RT_74
      STOF(ISTOF + 75) = RT_75
      STOF(ISTOF + 76) = RT_76
      STOF(ISTOF + 77) = RT_77
      STOF(ISTOF + 78) = RT_78
      STOF(ISTOF + 79) = RT_79
      STOF(ISTOF + 80) = RT_80
      STOF(ISTOF + 81) = RT_81
      STOF(ISTOF + 82) = RT_82
      STOF(ISTOF + 83) = RT_83
      STOF(ISTOF + 84) = RT_84
      STOF(ISTOF + 85) = RT_85
      STOF(ISTOF + 86) = RT_86
      STOF(ISTOF + 87) = RT_87
      STOF(ISTOF + 88) = RT_88
      STOF(ISTOF + 89) = RT_89
      STOF(ISTOF + 90) = RT_90
      STOF(ISTOF + 91) = RT_91
      STOF(ISTOF + 92) = RT_92
      STOF(ISTOF + 93) = RT_93
      STOF(ISTOF + 94) = RT_94
      STOF(ISTOF + 95) = RT_95
      STOF(ISTOF + 96) = RT_96
      STOF(ISTOF + 97) = RT_97
      STOF(ISTOF + 98) = RT_98
      STOF(ISTOF + 99) = RT_99
      STOF(ISTOF + 100) = RT_100
      STOF(ISTOF + 101) = RT_101
      STOF(ISTOF + 102) = RT_102
      STOF(ISTOF + 103) = RT_103
      STOF(ISTOF + 104) = RT_104
      STOF(ISTOF + 105) = RT_105
      STOF(ISTOF + 106) = RT_106
      STOF(ISTOF + 107) = RT_107
      STOF(ISTOF + 108) = RT_108
      STOF(ISTOF + 109) = RT_109
      STOF(ISTOF + 110) = RT_110
      STOF(ISTOF + 111) = RT_111
      STOF(ISTOF + 112) = RT_112
      STOF(ISTOF + 113) = RT_113
      STOF(ISTOF + 114) = RT_114
      STOF(ISTOF + 115) = RT_115
      STOF(ISTOF + 116) = RT_116
      STOF(ISTOF + 117) = RT_117
      STOF(ISTOF + 118) = RT_118
      STOF(ISTOF + 119) = RT_119
      STOF(ISTOF + 120) = RT_120
      STOF(ISTOF + 121) = RT_121
      STOF(ISTOF + 122) = RT_122
      STOF(ISTOF + 123) = RT_123
      STOF(ISTOF + 124) = RT_124
      STOF(ISTOF + 125) = RT_125
      STOF(ISTOF + 126) = RT_126
      STOF(ISTOF + 127) = RT_127
      STOF(ISTOF + 128) = RT_128
      STOF(ISTOF + 129) = RT_129
      STOF(ISTOF + 130) = RT_130
      STOF(ISTOF + 131) = RT_131
      STOF(ISTOF + 132) = RT_132
      STOF(ISTOF + 133) = RT_133
      STOF(ISTOF + 134) = RT_134
      STOF(ISTOF + 135) = RT_135
      STOF(ISTOF + 136) = RT_136
      STOF(ISTOF + 137) = RT_137
      STOF(ISTOF + 138) = RT_138
      STOF(ISTOF + 139) = RT_139
      STOF(ISTOF + 140) = RT_140
      STOF(ISTOF + 141) = RT_141
      STOF(ISTOF + 142) = RT_142
      STOF(ISTOF + 143) = RT_143
      STOF(ISTOF + 144) = RT_144
      STOF(ISTOF + 145) = RT_145
      STOF(ISTOF + 146) = RT_146
      STOF(ISTOF + 147) = RT_147
      STOF(ISTOF + 148) = RT_148
      STOF(ISTOF + 149) = RT_149
      STOF(ISTOF + 150) = RT_150
      STOF(ISTOF + 151) = RT_151
      STOF(ISTOF + 152) = RT_152
      STOF(ISTOF + 153) = RT_153
      STOF(ISTOF + 154) = RT_154
      STOF(ISTOF + 155) = RT_155
      STOF(ISTOF + 156) = RT_156
      STOF(ISTOF + 157) = RT_157
      STOF(ISTOF + 158) = RT_158
      STOF(ISTOF + 159) = RT_159
      STOF(ISTOF + 160) = RT_160
      STOF(ISTOF + 161) = RT_161
      STOF(ISTOF + 162) = RT_162
      STOF(ISTOF + 163) = RT_163
      STOF(ISTOF + 164) = RT_164
      STOF(ISTOF + 165) = RT_165
      STOF(ISTOF + 166) = RT_166
      STOF(ISTOF + 167) = RT_167
      STOF(ISTOF + 168) = RT_168
      STOF(ISTOF + 169) = RT_169
      STOF(ISTOF + 170) = RT_170
      STOF(ISTOF + 171) = RT_171
      STOF(ISTOF + 172) = RT_172
      STOF(ISTOF + 173) = RT_173
      STOF(ISTOF + 174) = RT_174
      STOF(ISTOF + 175) = RT_175
      STOF(ISTOF + 176) = RT_176
      STOF(ISTOF + 177) = RT_177
      STOF(ISTOF + 178) = RT_178
      STOF(ISTOF + 179) = RT_179
      STOF(ISTOF + 180) = RT_180
      STOF(ISTOF + 181) = RT_181
      STOF(ISTOF + 182) = RT_182
      STOF(ISTOF + 183) = RT_183
      STOF(ISTOF + 184) = RT_184
      STOF(ISTOF + 185) = RT_185
      STOF(ISTOF + 186) = RT_186
      STOF(ISTOF + 187) = RT_187
      STOF(ISTOF + 188) = RT_188
      STOF(ISTOF + 189) = RT_189
      STOF(ISTOF + 190) = RT_190
      STOF(ISTOF + 191) = RT_191
      STOF(ISTOF + 192) = RT_192
      STOF(ISTOF + 193) = RT_193
      STOF(ISTOF + 194) = RT_194
      STOF(ISTOF + 195) = RT_195
      STOF(ISTOF + 196) = RT_196
      STOF(ISTOF + 197) = RT_197
      STOF(ISTOF + 198) = RT_198
      STOF(ISTOF + 199) = RT_199
      STOF(ISTOF + 200) = RT_200
      STOF(ISTOF + 201) = RT_201
      STOF(ISTOF + 202) = RT_202
      STOF(ISTOF + 203) = RT_203
      STOF(ISTOF + 204) = RT_204
      STOF(ISTOF + 205) = RT_205
      STOF(ISTOF + 206) = RT_206
      STOF(ISTOF + 207) = RT_207
      STOF(ISTOF + 208) = RT_208
      STOF(ISTOF + 209) = RT_209
      STOF(ISTOF + 210) = RT_210
      STOF(ISTOF + 211) = RT_211
      STOF(ISTOF + 212) = RT_212
      STOF(ISTOF + 213) = RT_213
      STOF(ISTOF + 214) = RT_214
      STOF(ISTOF + 215) = RT_215
      STOF(ISTOF + 216) = RT_216
      STOF(ISTOF + 217) = RT_217
      STOF(ISTOF + 218) = RT_218
      STOF(ISTOF + 219) = RT_219
      STOF(ISTOF + 220) = RT_220
      STOF(ISTOF + 221) = RT_221
      STOF(ISTOF + 222) = RT_222
      STOF(ISTOF + 223) = RT_223
      STOF(ISTOF + 224) = RT_224
      STOF(ISTOF + 225) = RT_225
      STOF(ISTOF + 226) = RT_226
      STOF(ISTOF + 227) = RT_227
      STOF(ISTOF + 228) = RT_228
      STOF(ISTOF + 229) = RT_229
      STOF(ISTOF + 230) = RT_230
      STOF(ISTOF + 231) = RT_231


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 94
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------



!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------



!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[time-sig] Output of Simulation Time 

! 20:[compare] Single Input Level Comparator 

! 30:[gain] Gain Block 

! 40:[pgb] Output Channel 'Odp.skok.prop'

! 50:[time-sig] Output of Simulation Time 

! 60:[compare] Single Input Level Comparator 

! 70:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 80:[realpole] Real Pole 

! 90:[realpole] Real Pole 

! 100:[time-sig] Output of Simulation Time 

! 110:[pgb] Output Channel 'RT_27'

! 120:[compare] Single Input Level Comparator 

! 130:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 140:[gain] Gain Block 

! 150:[pgb] Output Channel 'Odp.imp.prop'

! 160:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 170:[realpole] Real Pole 

! 180:[realpole] Real Pole 

! 190:[pgb] Output Channel 'RT_31'

! 200:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 210:[realpole] Real Pole 

! 220:[realpole] Real Pole 

! 230:[pgb] Output Channel 'RT_35'

! 240:[time-sig] Output of Simulation Time 

! 250:[compare] Single Input Level Comparator 

! 260:[realpole] Real Pole 

! 270:[realpole] Real Pole 

! 280:[pgb] Output Channel 'RT_156'

! 290:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 300:[realpole] Real Pole 

! 310:[realpole] Real Pole 

! 320:[realpole] Real Pole 

! 330:[pgb] Output Channel 'RT_159'

! 340:[realpole] Real Pole 

! 350:[pgb] Output Channel 'RT_38'

! 360:[time-sig] Output of Simulation Time 

! 370:[compare] Single Input Level Comparator 

! 380:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 390:[pgb] Output Channel 'odp.skok.calk.ideal'

! 400:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 410:[realpole] Real Pole 

! 420:[realpole] Real Pole 

! 430:[pgb] Output Channel 'RT_41'

! 440:[realpole] Real Pole 

! 450:[realpole] Real Pole 

! 460:[pgb] Output Channel 'RT_161'

! 470:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 480:[realpole] Real Pole 

! 490:[realpole] Real Pole 

! 500:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 510:[pgb] Output Channel 'RT_44'

! 520:[realpole] Real Pole 

! 530:[pgb] Output Channel 'odp.skok.calk.rzecz'

! 540:[realpole] Real Pole 

! 550:[realpole] Real Pole 

! 560:[pgb] Output Channel 'RT_163'

! 570:[realpole] Real Pole 

! 580:[realpole] Real Pole 

! 590:[pgb] Output Channel 'RT_165'

! 600:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 610:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 620:[pgb] Output Channel 'odp.imp.calk.ideal'

! 630:[realpole] Real Pole 

! 640:[realpole] Real Pole 

! 650:[pgb] Output Channel 'RT_167'

! 660:[time-sig] Output of Simulation Time 

! 670:[compare] Single Input Level Comparator 

! 680:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 690:[gain] Gain Block 

! 700:[pgb] Output Channel 'k=3'

! 710:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 720:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 730:[realpole] Real Pole 

! 740:[pgb] Output Channel 'odp.imp.calk.rzecz'

! 750:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 760:[gain] Gain Block 

! 770:[pgb] Output Channel 'k=6'

! 780:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 790:[gain] Gain Block 

! 800:[pgb] Output Channel 'k=9'

! 810:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 820:[pgb] Output Channel 'odp.skok.roz.ideal'

! 830:[time-sig] Output of Simulation Time 

! 840:[compare] Single Input Level Comparator 

! 850:[gain] Gain Block 

! 860:[pgb] Output Channel 'k=3'

! 870:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 880:[realpole] Real Pole 

! 890:[pgb] Output Channel 'odp.skok.roz.ideal'

! 900:[gain] Gain Block 

! 910:[pgb] Output Channel 'k=6'

! 920:[time-sig] Output of Simulation Time 

! 930:[compare] Single Input Level Comparator 

! 940:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 950:[gain] Gain Block 

! 960:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 970:[pgb] Output Channel 'k=3'

! 980:[gain] Gain Block 

! 990:[pgb] Output Channel 'k=9'

! 1000:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1010:[gain] Gain Block 

! 1020:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1030:[pgb] Output Channel 'k=6'

! 1040:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1050:[gain] Gain Block 

! 1060:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1070:[pgb] Output Channel 'k=9'

! 1080:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 1090:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.37
      NRTCF = NRTCF + 1

! 1100:[pgb] Output Channel 'odp.imp.roz.ideal'

! 1110:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1120:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1130:[realpole] Real Pole 

! 1140:[pgb] Output Channel 'k=3'

! 1150:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 1160:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.37
      NRTCF = NRTCF + 1

! 1170:[realpole] Real Pole 

! 1180:[pgb] Output Channel 'odp.imp.roz.ideal'

! 1190:[time-sig] Output of Simulation Time 

! 1200:[compare] Single Input Level Comparator 

! 1210:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1220:[gain] Gain Block 

! 1230:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1240:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1250:[pgb] Output Channel 'k=3'

! 1260:[realpole] Real Pole 

! 1270:[pgb] Output Channel 'k=6'

! 1280:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1290:[gain] Gain Block 

! 1300:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1310:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1320:[pgb] Output Channel 'k=6'

! 1330:[realpole] Real Pole 

! 1340:[pgb] Output Channel 'k=9'

! 1350:[gain] Gain Block 

! 1360:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1370:[pgb] Output Channel 'k=9'

! 1380:[realpole] Real Pole 

! 1390:[pgb] Output Channel 'odp.skok.inercyjnego I rzedu'

! 1400:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1410:[realpole] Real Pole 

! 1420:[pgb] Output Channel 'k=3'

! 1430:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1440:[realpole] Real Pole 

! 1450:[pgb] Output Channel 'k=6'

! 1460:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1470:[realpole] Real Pole 

! 1480:[pgb] Output Channel 'k=9'

! 1490:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 1500:[realpole] Real Pole 

! 1510:[pgb] Output Channel 'odp.skok.inercyjnego I rzedu'

! 1520:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1530:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1540:[realpole] Real Pole 

! 1550:[pgb] Output Channel 'T=3'

! 1560:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1570:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1580:[realpole] Real Pole 

! 1590:[pgb] Output Channel 'T=6'

! 1600:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1610:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1620:[realpole] Real Pole 

! 1630:[realpole] Real Pole 

! 1640:[realpole] Real Pole 

! 1650:[pgb] Output Channel 'T=9'

! 1660:[pgb] Output Channel 'odp.skok.inercyjnego II rzedu'

! 1670:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1680:[realpole] Real Pole 

! 1690:[pgb] Output Channel 'T=3'

! 1700:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1710:[realpole] Real Pole 

! 1720:[pgb] Output Channel 'T=6'

! 1730:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 1740:[realpole] Real Pole 

! 1750:[realpole] Real Pole 

! 1760:[pgb] Output Channel 'odp.imp.inercyjnego II rzedu'

! 1770:[time-sig] Output of Simulation Time 

! 1780:[compare] Single Input Level Comparator 

! 1790:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1800:[realpole] Real Pole 

! 1810:[pgb] Output Channel 'T=9'

! 1820:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1830:[gain] Gain Block 

! 1840:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 1850:[pgb] Output Channel 'k=3'

! 1860:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1870:[gain] Gain Block 

! 1880:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 1890:[pgb] Output Channel 'k=6'

! 1900:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1910:[gain] Gain Block 

! 1920:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 1930:[pgb] Output Channel 'k=9'

! 1940:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 1950:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 1960:[realpole] Real Pole 

! 1970:[pgb] Output Channel 'k=3'

! 1980:[time-sig] Output of Simulation Time 

! 1990:[compare] Single Input Level Comparator 

! 2000:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,2.73,0.0)

! 2010:[pgb] Output Channel 'odp.skok.opoz'

! 2020:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2030:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2040:[realpole] Real Pole 

! 2050:[pgb] Output Channel 'k=6'

! 2060:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2070:[gain] Gain Block 

! 2080:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2090:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2100:[pgb] Output Channel 'k=3'

! 2110:[realpole] Real Pole 

! 2120:[pgb] Output Channel 'k=9'

! 2130:[gain] Gain Block 

! 2140:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2150:[pgb] Output Channel 'k=6'

! 2160:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2170:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,2.73,0.0)

! 2180:[pgb] Output Channel 'odp.skok.opoz'

! 2190:[gain] Gain Block 

! 2200:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2210:[pgb] Output Channel 'k=9'

! 2220:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2230:[realpole] Real Pole 

! 2240:[pgb] Output Channel 'k=3'

! 2250:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2260:[realpole] Real Pole 

! 2270:[pgb] Output Channel 'k=6'

! 2280:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2290:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2300:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2310:[realpole] Real Pole 

! 2320:[pgb] Output Channel 'k=9'

! 2330:[realpole] Real Pole 

! 2340:[pgb] Output Channel 'T=3'

! 2350:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2360:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2370:[realpole] Real Pole 

! 2380:[pgb] Output Channel 'T=6'

! 2390:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2400:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2410:[realpole] Real Pole 

! 2420:[pgb] Output Channel 'T=9'

! 2430:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2440:[realpole] Real Pole 

! 2450:[pgb] Output Channel 'T=3'

! 2460:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2470:[realpole] Real Pole 

! 2480:[pgb] Output Channel 'T=6'

! 2490:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 2.73
      NRTCF = NRTCF + 1

! 2500:[realpole] Real Pole 

! 2510:[pgb] Output Channel 'T=9'

! 2520:[time-sig] Output of Simulation Time 

! 2530:[compare] Single Input Level Comparator 

! 2540:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2550:[realpole] Real Pole 

! 2560:[pgb] Output Channel 'k=3'

! 2570:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2580:[realpole] Real Pole 

! 2590:[pgb] Output Channel 'k=6'

! 2600:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2610:[realpole] Real Pole 

! 2620:[pgb] Output Channel 'k=9'

! 2630:[time-sig] Output of Simulation Time 

! 2640:[compare] Single Input Level Comparator 

! 2650:[realpole] Real Pole 

! 2660:[pgb] Output Channel 'k=3'

! 2670:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2680:[realpole] Real Pole 

! 2690:[pgb] Output Channel 'T=3'

! 2700:[realpole] Real Pole 

! 2710:[pgb] Output Channel 'k=6'

! 2720:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2730:[realpole] Real Pole 

! 2740:[pgb] Output Channel 'T=6'

! 2750:[realpole] Real Pole 

! 2760:[pgb] Output Channel 'k=9'

! 2770:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2780:[realpole] Real Pole 

! 2790:[pgb] Output Channel 'T=9'

! 2800:[realpole] Real Pole 

! 2810:[pgb] Output Channel 'T=3'

! 2820:[realpole] Real Pole 

! 2830:[pgb] Output Channel 'T=6'

! 2840:[realpole] Real Pole 

! 2850:[pgb] Output Channel 'T=9'

! 2860:[time-sig] Output of Simulation Time 

! 2870:[compare] Single Input Level Comparator 

! 2880:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2890:[gain] Gain Block 

! 2900:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,2.73,0.0)

! 2910:[pgb] Output Channel 'k=3'

! 2920:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2930:[gain] Gain Block 

! 2940:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,2.73,0.0)

! 2950:[pgb] Output Channel 'k=6'

! 2960:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 2970:[gain] Gain Block 

! 2980:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,2.73,0.0)

! 2990:[pgb] Output Channel 'k=9'

! 3000:[time-sig] Output of Simulation Time 

! 3010:[compare] Single Input Level Comparator 

! 3020:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 3030:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,3.0,0.0)

! 3040:[pgb] Output Channel 'T=3'

! 3050:[gain] Gain Block 

! 3060:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,2.73,0.0)

! 3070:[pgb] Output Channel 'k=3'

! 3080:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 3090:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,6.0,0.0)

! 3100:[pgb] Output Channel 'T=6'

! 3110:[gain] Gain Block 

! 3120:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,2.73,0.0)

! 3130:[pgb] Output Channel 'k=6'

! 3140:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 3150:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,9.0,0.0)

! 3160:[pgb] Output Channel 'T=9'

! 3170:[gain] Gain Block 

! 3180:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,2.73,0.0)

! 3190:[pgb] Output Channel 'k=9'

! 3200:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,3.0,0.0)

! 3210:[pgb] Output Channel 'T=3'

! 3220:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,6.0,0.0)

! 3230:[pgb] Output Channel 'T=6'

! 3240:[tdelay] Delay Function 
      CALL DELAY2_CFG(0,100,0,9.0,0.0)

! 3250:[pgb] Output Channel 'T=9'

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


      RETURN
      END

