#line 1 "Main.f"
/* Main.f -- translated by f2c (version 19990326).
   You must link the resulting object file with the libraries:
	-lf2c -lm   (in that order)
*/

#include "f2c.h"

#line 1 "Main.f"
/* Common Block Declarations */

struct {
    integer e_ndim__[50];
} ndim_;

#define ndim_1 ndim_

struct {
    doublecomplex storc[10000];
    doublereal storf[10000];
    integer stori[10000];
    logical storl[10000];
    integer nstorc, nstorf, nstori, nstorl, this__;
} storage_;

#define storage_1 storage_

struct {
    doublereal rdc[400000]	/* was [200][200][10] */, ccin[2000]	/* 
	    was [200][10] */, vdc[2000]	/* was [200][10] */, gm[400000]	/* 
	    was [200][200][10] */, ccgm[2000]	/* was [200][10] */, ccgmd[
	    2000]	/* was [200][10] */, ccli[2000]	/* was [200][10] */, 
	    ggin[2000]	/* was [200][10] */, ca[200], cdctr[700]	/* 
	    was [10][70] */, cdctro[700]	/* was [10][70] */;
    integer mbus[10];
    logical idealss[10], enabccin[2000]	/* was [200][10] */;
} s0_;

#define s0_1 s0_

struct {
    doublereal time, delt, print, fintim;
    logical timezero, firststep, laststep, onstep;
} s1_;

#define s1_1 s1_

struct {
    doublereal stor[50000];
    integer nexc;
} s2_;

#define s2_1 s2_

struct {
    doublereal var[1], con[100], pgb[1030];
    logical update_ag__;
} s4_;

#define s4_1 s4_

struct {
    doublereal cbr[20000]	/* was [2000][10] */, ccbr[20000]	/* 
	    was [2000][10] */, ccbrd[20000]	/* was [2000][10] */, ebr[
	    20000]	/* was [2000][10] */, ebrd[20000]	/* was [2000][
	    10] */, ebron[20000]	/* was [2000][10] */, ebrof[20000]	
	    /* was [2000][10] */, swlevl[20000]	/* was [2000][10] */, geq[
	    20000]	/* was [2000][10] */, geqon[20000]	/* was [2000][
	    10] */, geqof[20000]	/* was [2000][10] */, geqd[20000]	
	    /* was [2000][10] */, rlg[20000]	/* was [2000][10] */, rcg[
	    20000]	/* was [2000][10] */, rcl[20000]	/* was [2000][
	    10] */, rsc[20000]	/* was [2000][10] */, rsl[20000]	/* 
	    was [2000][10] */, ccl[20000]	/* was [2000][10] */, ccld[
	    20000]	/* was [2000][10] */, ccc[20000]	/* was [2000][
	    10] */, cccd[20000]	/* was [2000][10] */, g2l[20000]	/* 
	    was [2000][10] */, g2c[20000]	/* was [2000][10] */, v12l[
	    20000]	/* was [2000][10] */, v20l[20000]	/* was [2000][
	    10] */;
    integer nsw[10], brnsw[20000]	/* was [2000][10] */, iet[20000]	
	    /* was [2000][10] */, ief[20000]	/* was [2000][10] */, thisbr[
	    20000]	/* was [2000][10] */;
    logical resistor[20000]	/* was [2000][10] */, inductor[20000]	/* 
	    was [2000][10] */, capacitr[20000]	/* was [2000][10] */, source[
	    20000]	/* was [2000][10] */, switch__[20000]	/* was [2000][
	    10] */, idealbr[20000]	/* was [2000][10] */, openbr[20000]	
	    /* was [2000][10] */, defrdbr[20000]	/* was [2000][10] */, 
	    flipidlbr[20000]	/* was [2000][10] */, geqchange[2000];
} branches_;

#define branches_1 branches_

struct {
    doublecomplex stoc[20000];
    doublereal stof[20000];
    integer stoi[20000], txfr[400]	/* was [100][4] */, nstol, nstoi, 
	    nstof, nstoc, ntxfr, nvar, npgb, nnode, nsubs, nbrch[10], nxfmr, 
	    node[2000], subs[1000], testss[2000];
    logical stol[20000], guisoc;
    char ss_ref_style__[3];
} pscadv3_;

#define pscadv3_1 pscadv3_

struct {
    char dumlin[72], section[72], filename[72];
    integer iunit, iunitout;
    logical netdata;
    char inam[34], tnam[34], inam1[34], onam[34], snam[34], rtsnam[34], mnam[
	    34], mapname[34];
} fnames_;

#define fnames_1 fnames_

struct {
    doublereal tx[50];
    integer txrx[500], ntxrx;
} radiolinks_;

#define radiolinks_1 radiolinks_

/* Table of constant values */

static integer c__0 = 0;
static doublereal c_b6 = 1.;
static doublereal c_b7 = 0.;
static doublereal c_b27 = 2.73;
static doublereal c_b29 = -100.;
static doublereal c_b30 = 100.;
static integer c__1 = 1;
static doublereal c_b42 = 3.;
static doublereal c_b43 = 2.37;
static doublereal c_b45 = -10.;
static doublereal c_b46 = 10.;
static integer c__100 = 100;
static doublereal c_b142 = 6.;
static doublereal c_b158 = 9.;

/* ======================================================================= */
/* Generated by  : PSCAD v4.2.1 */

/* Warning:  The content of this file is automatically generated. */
/*           Do not modify, as any changes made here will be lost! */
/* ----------------------------------------------------------------------- */
/* Component     : Main */
/* Description   : */
/* ----------------------------------------------------------------------- */
/* ======================================================================= */
/* Subroutine */ int dsdyn_()
{
    /* Builtin functions */
    /* Subroutine */ int s_copy();

    /* Local variables */
    static doublereal rt_1__, rt_2__, rt_3__, rt_4__, rt_5__, rt_6__, rt_7__, 
	    rt_8__, rt_9__;
    static integer ipgb;
    static doublereal rt_10__, rt_11__, rt_12__, rt_13__, rt_14__, rt_15__, 
	    rt_16__, rt_17__, rt_18__, rt_19__, rt_20__, rt_21__, rt_22__, 
	    rt_23__, rt_24__, rt_25__, rt_26__, rt_27__, rt_28__, rt_29__, 
	    rt_30__, rt_31__, rt_32__, rt_33__, rt_34__, rt_35__, rt_36__, 
	    rt_37__, rt_38__;
    extern doublereal delay_();
    static doublereal rvd2_1__[2], rvd2_2__[2];
    static integer istof;
    extern doublereal deriv1_(), realpole_(), emtdc_xint__();
    extern /* Subroutine */ int emtdc_x2comp__(), emtdc_openfile__(), 
	    emtdc_closefile__(), emtdc_gotosection__();

/* --------------------------------------- */
/* Standard includes */
/* --------------------------------------- */
/*     -------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING THE SIZE OF THE SYSTEM */
/*     -------------------------------------------------- */
/*     ND1  = MAX. NO. NODES PER SUBSYSTEM */
/*     ND2  = MAX. NO. SUBSYSTEMS */
/*     ND7  = MAX. NO. SUBSYSTEMS IN ALL PAGES */

/*     ---------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING TRANSFORMERS */
/*     ---------------------------------------- */
/*     ND3  = MAX. NO. MUTUALLY COUPLED WINDINGS, */
/*     ND4  = MAX. NO. TRANSFORMERS */

/*     ---------------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING DISTRIBUTED TRANSMISSION LINES */
/*     ---------------------------------------------------------- */
/*     ND5  = MAX. NO. OF MODES OR PHASES */
/*     ND6  = MAX. NO. OF LINES */
/*     ND8  = MAX. NO. OF POLES FOR FREQDEP MODEL */

/*     ---------------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING UMEC TRANSFORMER */
/*     (CURRENTLY UNUSED) */
/*     ---------------------------------------------------------- */

/*     -------------------------------------------- */
/*     PARAMETER FOR COMMON BLOCK S2 ( STOR(), NEXC */
/*     -------------------------------------------- */
/*     ND10  = MAX. NO. STOR LOCATIONS */

/*     -------------------------------------------------- */
/*     PARAMETERS FOR COMMON BLOCK S4 ( VAR(),CON(),PGB() */
/*     -------------------------------------------------- */
/*     ND11  = MAX. NO. VAR'S */
/*     ND12  = MAX. NO. CON'S */
/*     ND13  = MAX. NO. PGB'S */

/*     ----------------------------------------------------------- */
/*     PARAMETERS FOR THE MAXIMUM NUMBER OF BRANCHES PER SUBSYSTEM */
/*     ----------------------------------------------------------- */
/*     ND14  = MAX. NO. OF POSITIVE NUMBERED BRANCHES (obsolete) */
/*     ND15  = MAX. NO. OF NUMBERED BRANCHES */
/*     ND16  = MAX. NO. OF THEVININ SOURCES (obsolete) */

/*     ------------------------------------------------------------- */
/*     PARAMETERS FOR THE MAXIMUM NUMBER OF INTERPOLATING SWITCHINGS */
/*     PER SUBSYSTEM */
/*     ------------------------------------------------------------- */
/*     ND17  = MAX. NO. OF ALLOWABLE SWITCHING SUBROUTINES USING */
/*             INTERPOLATION PER SUBSYSTEM (Obsolete) */

/*     ------------------------------------------------------------- */
/*     PARAMETER FOR THE MAXIMUM NUMBER OF B6P110 VALVE GROUP MODELS */
/*     ------------------------------------------------------------- */
/*     ND18  = MAX. NO. OF B6P110 VALVE GROUP MODELS */

/*     ------------------------------------------------------------- */
/*     PARAMETER FOR THE MAXIMUM NUMBER OF ELEMENTS IN THE LOWER */
/*     TRIANGULARIZED CONDUCTANCE MATRIX PER SUBSYSTEM */

/*     A FULL MATRIX WOULD HAVE A MAXIMUM OF ( N*N - N ) / 2 ELEMENTS */
/*     WHERE N IS THE NUMBER OF NODES IN THE SUBSYSTEM */
/*     ------------------------------------------------------------- */
/*     ND19  = MAX. NO. OF SPARSITY ENTRIES PER SUBSYSTEM */

/* Node Map */
/* Pages */
/* NSTOL */
/* NSTOI */
/* NSTOF */
/* NSTOC */
/* NSTORL */
/* NSTORI */
/* NSTORF */
/* NSTORC */
/* TOTAL # OF TRAVELLING WAVE BUFFERS */
/* TOTAL # OF TERMS OF CONSTANT TRANSFORM */
/* TOTAL # OF POLES FOR TRANSFORM */
/* TOTAL # OF POLES FOR ATTENUATION */
/* TOTAL # OF POLES FOR SURGE IMPEDANCE */
/* TOTAL # OF MODES FOR BERGERON/FRE-DEP MOD */
/* TOTAL # OF WIRELESS RADIO TRANSMITTERS */
/* TOTAL # OF WIRELESS RADIO TRANSMITTERS & */
/* TOTAL # OF SPARSE ENTRIES IN 'DU' (HAMONI */
/* Phase Domain Model Dimensions */
/* TOTAL # OF NODES */
/* MAXIMUM NUMBER OF PHASE DOMAIN TLINES */
/* TOTAL   # OF MODES (PHASE DOMAIN) */
/* MAXIMUM # OF MODES (PHASE DOMAIN) */
/* TOTAL   # OF TRAVELLING WAVE BUFFERS (PHA */
/* TOTAL   # OF PROPAGATION BUFFERS (PHASE D */
/* TOTAL   # OF HSERC ELEMENTS (PHASE DOMAIN */
/* TOTAL   # OF YCSERC ELEMENTS (PHASE DOMAI */
/* TOTAL   # OF XHK ELEMENTS (PHASE DOMAIN) */
/* MAXIMUM NUMBER OF POLE/ZEROES (PHASE DOMA */
/* COMMON BLOCK */
/* Spare */
/* ====================================================================== */
/* EMTDC Constants */
/* ====================================================================== */
/* *** */
/* * Values of PI, its fractions and multiples */
/* *** */
/* *** */
/* * Sqare roots */
/* *** */
/* *** */
/* * 1/3 and 2/3 */
/* *** */
/* Type conversion routines */
/* ====================================================================== */
/* ====================================================================== */
/* Common block variables for EMTDC model data STORage */
/* ====================================================================== */
/* STORage Array index usage counters */
/* STORage Arrays (Temporary sizes) */
/* storage: STORx */
/* Logical */
/* Integer */
/* Real */
/* Common Block for EMTDC model data storage */
/* Complex */
/*     CDCTRO = Total winding current including saturation current */
/* TIME    : current time of simulation in seconds */
/* DELT    : simulation time step in seconds */
/* ICH     : Obsolete */
/* PRINT   : print step interval in seconds */
/* FINTIM  : simulation finish tim ein seconds */
/* TIMEZERO: true when time is zero */
/* FIRSTSTEP: true for first step starting from data file or snap file */
/* LASTSTEP: true for last step of the run */
/* ONSTEP:   true if calling from dsdyn/dsout */
/* Data storage array for backward compatibility */
/* Real data storage ( from V3.0 version ) */
/* Running index of STOR array */
/* ======================================================================= */
/* Branch Types (Constants) */
/* ======================================================================= */
/* Breakers */
/* Power Electronic Switches (PESWITCH type) */
/* SWINT5 Breaker */
/* Diode */
/* Thyistor */
/* GTO */
/* IGBT */
/* MOSFET */
/* Arrestors */
/* Transistor */
/* Voltage Sources */
/* Gapless Metal Oxide Arrestor */
/* Current Sources */
/* Branch voltage source */
/* Single phase current source */
/* ======================================================================= */
/* Common Blocks */
/* ======================================================================= */
/* Three phase current source */
/* Branch current */
/* Equivalent history current */
/* Equivalent history current from step */
/* Internal voltage magnitude */
/* EBR from previous time step */
/* ON state resistance */
/* OFF state resistance */
/* Switching level (I,V,or time) */
/* Equivalent conductance */
/* Equivalent ON state conductance */
/* Equivalent OFF state conductance */
/* Equivalent conductance from last step */
/* Factor used in collapsing RLC branch */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/* Total # of switched in SS */
/* Branch # ( switch => branch ) */
/* From node of branch +ve curr. flows o */
/* To node of branch, +ve curr. flows in */
/* Starting location of data storage */
/* True if has resistance */
/* True if has inductance */
/* True if has capacitance */
/* True if has internal source */
/* True if switchable */
/* True if zero impedance (ideal) */
/* True if switch is open (high R) */
/* True if attributes undecided */
/* Flag if an ideal branch is collapsed */
/* True if branch switched w/o interp */
/* =============================================================================== */
/* Common block variables */
/* =============================================================================== */
/* Array index usage counters */
/* Storage: STOx */
/* Control, Monitor */
/* Node, Transformer */
/* Subsystems */
/* DSDYN <-> DSOUT tran */
/* Storage Arrays */
/* Branch */
/* Temporary sizes */
/* Operational Mode */
/* true: Socket exists */
/* Common Block for PSCAD V3 linkage */
/*  NAMES OF ALL INPUT / OUTPUT FILES */
/*  INAM  =  INPUT FILE NAME ( SNAPSHOT OR DATA FILES ) */
/*  TNAM  =  TABLE FILE NAME ( Nodes Table file ) */
/*  INAM1 =  INPUT INCLUDE FILE NAME */
/*  FILENAME =  DATA FILE NAME */
/*  MAPNAME  = Name of the map to be read for this page */
/*  IUNIT =  CURRENT INPUT FILE UNIT NUMBER */
/*  IUNITOUT = STARTING UNIT # FOR OUTPUT FILES */
/*  ONAM  =  OUTPUT FILE NAME ( PGB INFORMATION AND/OR PRINT PLOTS ) */
/*  SNAM  =  END OF RUN SNAPSHOT FILE NAME */
/*           SNAM IF ONLY 1 SNAP TO BE WRITTEN OR MULTIPLE TO SAME FILE */
/*           SNAP-01,SNAP-02 ...  IF INCREMENTAL SNAP TO DIFFERENT FILE */
/*  RTSNAM = Same as SNAM but for runtime snapshot files */
/*  MNAM  =  MULTIPLE RUN FILE NAME */
/*  DUMLIN=  ARRAY USED FOR STORING CURRENT DATA LINE READ */
/*  SECTION= Name of the section last read */
/*  DATALINE = True if nodes from map file are to be read */
/* true while reading network data */
/* --------------------------------------- */
/* Function/Subroutine Declarations */
/* --------------------------------------- */
/*     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation' */
/* Derivative Function */
/* 'Integrator /w Interpolation' */
/* Real Pole */
/* --------------------------------------- */
/* Variable Declarations */
/* --------------------------------------- */
/* Subroutine Parameters */
/* Electrical Node Indexes */
/* Control Signals */
/* Delay Line */
/* Internal Variables */
/* Indexing variables */
/* Storage Indexes */
/* Control/Monitoring */
/* --------------------------------------- */
/* Record local indexes */
/* --------------------------------------- */
/* Dsdyn <-> Dsout transfer index storage */
/* SS/Node/Branch/Xfmr */
#line 76 "Main.f"
    ++pscadv3_1.ntxfr;
#line 77 "Main.f"
    pscadv3_1.txfr[pscadv3_1.ntxfr - 1] = pscadv3_1.nstol;
#line 78 "Main.f"
    pscadv3_1.txfr[pscadv3_1.ntxfr + 99] = pscadv3_1.nstoi;
#line 79 "Main.f"
    pscadv3_1.txfr[pscadv3_1.ntxfr + 199] = pscadv3_1.nstof;
/* Record Offset and Increment Storage Counters */
#line 82 "Main.f"
    istof = pscadv3_1.nstof;
#line 83 "Main.f"
    pscadv3_1.nstof += 38;
#line 84 "Main.f"
    ipgb = pscadv3_1.npgb;
#line 85 "Main.f"
    pscadv3_1.npgb += 17;
#line 86 "Main.f"
    pscadv3_1.nnode += 2;
/* --------------------------------------- */
/* Transfers from storage arrays */
/* --------------------------------------- */
#line 93 "Main.f"
    rt_1__ = pscadv3_1.stof[istof];
#line 94 "Main.f"
    rt_2__ = pscadv3_1.stof[istof + 1];
#line 95 "Main.f"
    rt_3__ = pscadv3_1.stof[istof + 2];
#line 96 "Main.f"
    rt_4__ = pscadv3_1.stof[istof + 3];
#line 97 "Main.f"
    rt_5__ = pscadv3_1.stof[istof + 4];
#line 98 "Main.f"
    rt_6__ = pscadv3_1.stof[istof + 5];
#line 99 "Main.f"
    rt_7__ = pscadv3_1.stof[istof + 6];
#line 100 "Main.f"
    rt_8__ = pscadv3_1.stof[istof + 7];
#line 101 "Main.f"
    rt_9__ = pscadv3_1.stof[istof + 8];
#line 102 "Main.f"
    rt_10__ = pscadv3_1.stof[istof + 9];
#line 103 "Main.f"
    rt_11__ = pscadv3_1.stof[istof + 10];
#line 104 "Main.f"
    rt_12__ = pscadv3_1.stof[istof + 11];
#line 105 "Main.f"
    rt_13__ = pscadv3_1.stof[istof + 12];
#line 106 "Main.f"
    rt_14__ = pscadv3_1.stof[istof + 13];
#line 107 "Main.f"
    rt_15__ = pscadv3_1.stof[istof + 14];
#line 108 "Main.f"
    rt_16__ = pscadv3_1.stof[istof + 15];
#line 109 "Main.f"
    rt_17__ = pscadv3_1.stof[istof + 16];
#line 110 "Main.f"
    rt_18__ = pscadv3_1.stof[istof + 17];
#line 111 "Main.f"
    rt_19__ = pscadv3_1.stof[istof + 18];
#line 112 "Main.f"
    rt_20__ = pscadv3_1.stof[istof + 19];
#line 113 "Main.f"
    rt_21__ = pscadv3_1.stof[istof + 20];
#line 114 "Main.f"
    rt_22__ = pscadv3_1.stof[istof + 21];
#line 115 "Main.f"
    rt_23__ = pscadv3_1.stof[istof + 22];
#line 116 "Main.f"
    rt_24__ = pscadv3_1.stof[istof + 23];
#line 117 "Main.f"
    rt_25__ = pscadv3_1.stof[istof + 24];
#line 118 "Main.f"
    rt_26__ = pscadv3_1.stof[istof + 25];
#line 119 "Main.f"
    rt_27__ = pscadv3_1.stof[istof + 26];
#line 120 "Main.f"
    rt_28__ = pscadv3_1.stof[istof + 27];
#line 121 "Main.f"
    rt_29__ = pscadv3_1.stof[istof + 28];
#line 122 "Main.f"
    rt_30__ = pscadv3_1.stof[istof + 29];
#line 123 "Main.f"
    rt_31__ = pscadv3_1.stof[istof + 30];
#line 124 "Main.f"
    rt_32__ = pscadv3_1.stof[istof + 31];
#line 125 "Main.f"
    rt_33__ = pscadv3_1.stof[istof + 32];
#line 126 "Main.f"
    rt_34__ = pscadv3_1.stof[istof + 33];
#line 127 "Main.f"
    rt_35__ = pscadv3_1.stof[istof + 34];
#line 128 "Main.f"
    rt_36__ = pscadv3_1.stof[istof + 35];
#line 129 "Main.f"
    rt_37__ = pscadv3_1.stof[istof + 36];
#line 130 "Main.f"
    rt_38__ = pscadv3_1.stof[istof + 37];
/* --------------------------------------- */
/* Transfer from Imports */
/* --------------------------------------- */
/* --------------------------------------- */
/* Electrical Node Lookup */
/* --------------------------------------- */
/* --------------------------------------- */
/* Read Model data (if any) */
/* --------------------------------------- */
#line 146 "Main.f"
    if (s1_1.timezero) {
#line 147 "Main.f"
	s_copy(fnames_1.filename, "Main.dta", (ftnlen)72, (ftnlen)8);
#line 148 "Main.f"
	emtdc_openfile__();
#line 149 "Main.f"
	s_copy(fnames_1.section, "DATADSD:", (ftnlen)72, (ftnlen)8);
#line 150 "Main.f"
	emtdc_gotosection__();
#line 151 "Main.f"
    }
/* --------------------------------------- */
/* Generated code from module definition */
/* --------------------------------------- */
/* 10:[time-sig] Output of Simulation Time */
#line 159 "Main.f"
    rt_1__ = s1_1.time;
/* 20:[compare] Single Input Level Comparator */

#line 163 "Main.f"
    emtdc_x2comp__(&c__0, &c__0, &c_b6, &rt_1__, &c_b7, &c_b7, &c_b6, 
	    rvd2_1__);
#line 164 "Main.f"
    rt_2__ = rvd2_1__[0];
/* 30:[gain] Gain Block */
/*  Gain */
#line 168 "Main.f"
    rt_3__ = rt_2__ * 3.;

/* 40:[pgb] Output Channel 'Odp.skok.prop' */
#line 173 "Main.f"
    s4_1.pgb[ipgb] = rt_3__;
/* 50:[time-sig] Output of Simulation Time */
#line 176 "Main.f"
    rt_4__ = s1_1.time;
/* 60:[compare] Single Input Level Comparator */

#line 180 "Main.f"
    emtdc_x2comp__(&c__0, &c__0, &c_b6, &rt_4__, &c_b7, &c_b7, &c_b6, 
	    rvd2_1__);
#line 181 "Main.f"
    rt_5__ = rvd2_1__[0];
/* 70:[derivative] Derivative with a time constant */
/*  Derivative */
#line 185 "Main.f"
    rt_7__ = deriv1_(&c_b6, &rt_5__);

/* 80:[gain] Gain Block */
/*  Gain */
#line 190 "Main.f"
    rt_6__ = rt_7__ * 3.;

/* 90:[pgb] Output Channel 'Odp.imp.prop' */
#line 195 "Main.f"
    s4_1.pgb[ipgb + 1] = rt_6__;
/* 100:[time-sig] Output of Simulation Time */
#line 198 "Main.f"
    rt_8__ = s1_1.time;
/* 110:[compare] Single Input Level Comparator */

#line 202 "Main.f"
    emtdc_x2comp__(&c__0, &c__0, &c_b6, &rt_8__, &c_b7, &c_b7, &c_b6, 
	    rvd2_1__);
#line 203 "Main.f"
    rt_23__ = rvd2_1__[0];
/* 120:[integral] Interpolated Integrator */
#line 206 "Main.f"
    rvd2_1__[0] = rt_23__;
#line 207 "Main.f"
    rvd2_1__[1] = 0.;
#line 208 "Main.f"
    rvd2_2__[0] = 0.;
#line 209 "Main.f"
    rvd2_2__[1] = 0.;

#line 211 "Main.f"
    rt_9__ = emtdc_xint__(&c__0, &c__0, &c__0, &c_b7, &c_b27, &c_b7, &c_b29, &
	    c_b30, rvd2_2__, rvd2_1__);
/* 130:[pgb] Output Channel 'odp.skok.calk.ideal' */
#line 216 "Main.f"
    s4_1.pgb[ipgb + 2] = rt_9__;
/* 140:[integral] Interpolated Integrator */
#line 219 "Main.f"
    rvd2_1__[0] = rt_23__;
#line 220 "Main.f"
    rvd2_1__[1] = 0.;
#line 221 "Main.f"
    rvd2_2__[0] = 0.;
#line 222 "Main.f"
    rvd2_2__[1] = 0.;

#line 224 "Main.f"
    rt_10__ = emtdc_xint__(&c__0, &c__0, &c__0, &c_b7, &c_b27, &c_b7, &c_b29, 
	    &c_b30, rvd2_2__, rvd2_1__);
/* 150:[realpole] Real Pole */
/*  Real_Pole */
#line 229 "Main.f"
    rt_11__ = realpole_(&c__0, &c__1, &c__0, &c_b42, &c_b43, &rt_10__, &c_b7, 
	    &c_b45, &c_b46);
/* 160:[pgb] Output Channel 'odp.skok.calk.rzecz' */
#line 233 "Main.f"
    s4_1.pgb[ipgb + 3] = rt_11__;
/* 170:[derivative] Derivative with a time constant */
/*  Derivative */
#line 237 "Main.f"
    rt_12__ = deriv1_(&c_b27, &rt_23__);

/* 180:[integral] Interpolated Integrator */
#line 241 "Main.f"
    rvd2_1__[0] = rt_12__;
#line 242 "Main.f"
    rvd2_1__[1] = 0.;
#line 243 "Main.f"
    rvd2_2__[0] = 0.;
#line 244 "Main.f"
    rvd2_2__[1] = 0.;

#line 246 "Main.f"
    rt_14__ = emtdc_xint__(&c__0, &c__0, &c__0, &c_b7, &c_b27, &c_b7, &c_b29, 
	    &c_b30, rvd2_2__, rvd2_1__);
/* 190:[pgb] Output Channel 'odp.imp.calk.ideal' */
#line 251 "Main.f"
    s4_1.pgb[ipgb + 4] = rt_14__;
/* 200:[derivative] Derivative with a time constant */
/*  Derivative */
#line 255 "Main.f"
    rt_13__ = deriv1_(&c_b27, &rt_23__);

/* 210:[integral] Interpolated Integrator */
#line 259 "Main.f"
    rvd2_1__[0] = rt_13__;
#line 260 "Main.f"
    rvd2_1__[1] = 0.;
#line 261 "Main.f"
    rvd2_2__[0] = 0.;
#line 262 "Main.f"
    rvd2_2__[1] = 0.;

#line 264 "Main.f"
    rt_15__ = emtdc_xint__(&c__0, &c__0, &c__0, &c_b7, &c_b27, &c_b7, &c_b29, 
	    &c_b30, rvd2_2__, rvd2_1__);
/* 220:[realpole] Real Pole */
/*  Real_Pole */
#line 269 "Main.f"
    rt_16__ = realpole_(&c__0, &c__1, &c__0, &c_b42, &c_b43, &rt_15__, &c_b7, 
	    &c_b45, &c_b46);
/* 230:[pgb] Output Channel 'odp.imp.calk.rzecz' */
#line 273 "Main.f"
    s4_1.pgb[ipgb + 5] = rt_16__;
/* 240:[derivative] Derivative with a time constant */
/*  Derivative */
#line 277 "Main.f"
    rt_17__ = deriv1_(&c_b27, &rt_23__);

/* 250:[pgb] Output Channel 'odp.skok.roz.ideal' */
#line 282 "Main.f"
    s4_1.pgb[ipgb + 6] = rt_17__;
/* 260:[derivative] Derivative with a time constant */
/*  Derivative */
#line 286 "Main.f"
    rt_18__ = deriv1_(&c_b27, &rt_23__);

/* 270:[realpole] Real Pole */
/*  Real_Pole */
#line 291 "Main.f"
    rt_19__ = realpole_(&c__0, &c__1, &c__0, &c_b42, &c_b43, &rt_18__, &c_b7, 
	    &c_b45, &c_b46);
/* 280:[pgb] Output Channel 'odp.skok.roz.ideal' */
#line 295 "Main.f"
    s4_1.pgb[ipgb + 7] = rt_19__;
/* 290:[realpole] Real Pole */
/*  Real_Pole */
#line 299 "Main.f"
    rt_20__ = realpole_(&c__0, &c__1, &c__0, &c_b42, &c_b43, &rt_23__, &c_b7, 
	    &c_b45, &c_b46);
/* 300:[pgb] Output Channel 'odp.skok.inercyjnego I rzedu' */
#line 303 "Main.f"
    s4_1.pgb[ipgb + 8] = rt_20__;
/* 310:[realpole] Real Pole */
/*  Real_Pole */
#line 307 "Main.f"
    rt_21__ = realpole_(&c__0, &c__1, &c__0, &c_b6, &c_b27, &rt_23__, &c_b7, &
	    c_b45, &c_b46);
/* 320:[realpole] Real Pole */
/*  Real_Pole */
#line 311 "Main.f"
    rt_22__ = realpole_(&c__0, &c__1, &c__0, &c_b42, &c_b43, &rt_21__, &c_b7, 
	    &c_b45, &c_b46);
/* 330:[pgb] Output Channel 'odp.skok.inercyjnego II rzedu' */
#line 315 "Main.f"
    s4_1.pgb[ipgb + 9] = rt_22__;
/* 340:[tdelay] Delay Function */
/*  Delay */
#line 319 "Main.f"
    rt_24__ = delay_(&c_b27, &c__100, &rt_23__);

/* 350:[pgb] Output Channel 'odp.skok.opoz' */
#line 324 "Main.f"
    s4_1.pgb[ipgb + 10] = rt_24__;
/* 360:[time-sig] Output of Simulation Time */
#line 327 "Main.f"
    rt_27__ = s1_1.time;
/* 370:[compare] Single Input Level Comparator */

#line 331 "Main.f"
    emtdc_x2comp__(&c__0, &c__0, &c_b6, &rt_27__, &c_b7, &c_b7, &c_b6, 
	    rvd2_1__);
#line 332 "Main.f"
    rt_36__ = rvd2_1__[0];
/* 380:[realpole] Real Pole */
/*  Real_Pole */
#line 336 "Main.f"
    rt_25__ = realpole_(&c__0, &c__1, &c__0, &c_b6, &c_b27, &rt_36__, &c_b7, &
	    c_b45, &c_b46);
/* 390:[realpole] Real Pole */
/*  Real_Pole */
#line 340 "Main.f"
    rt_26__ = realpole_(&c__0, &c__1, &c__0, &c_b42, &c_b43, &rt_25__, &c_b7, 
	    &c_b45, &c_b46);
/* 400:[pgb] Output Channel 'k =3' */
#line 344 "Main.f"
    s4_1.pgb[ipgb + 11] = rt_26__;
/* 410:[realpole] Real Pole */
/*  Real_Pole */
#line 348 "Main.f"
    rt_28__ = realpole_(&c__0, &c__1, &c__0, &c_b6, &c_b27, &rt_36__, &c_b7, &
	    c_b45, &c_b46);
/* 420:[realpole] Real Pole */
/*  Real_Pole */
#line 352 "Main.f"
    rt_29__ = realpole_(&c__0, &c__1, &c__0, &c_b142, &c_b43, &rt_28__, &c_b7,
	     &c_b45, &c_b46);
/* 430:[pgb] Output Channel 'k =6' */
#line 356 "Main.f"
    s4_1.pgb[ipgb + 12] = rt_29__;
/* 440:[realpole] Real Pole */
/*  Real_Pole */
#line 360 "Main.f"
    rt_30__ = realpole_(&c__0, &c__1, &c__0, &c_b6, &c_b27, &rt_36__, &c_b7, &
	    c_b45, &c_b46);
/* 450:[realpole] Real Pole */
/*  Real_Pole */
#line 364 "Main.f"
    rt_31__ = realpole_(&c__0, &c__1, &c__0, &c_b158, &c_b43, &rt_30__, &c_b7,
	     &c_b45, &c_b46);
/* 460:[pgb] Output Channel 'k =9' */
#line 368 "Main.f"
    s4_1.pgb[ipgb + 13] = rt_31__;
/* 470:[realpole] Real Pole */
/*  Real_Pole */
#line 372 "Main.f"
    rt_32__ = realpole_(&c__0, &c__1, &c__0, &c_b6, &c_b42, &rt_36__, &c_b7, &
	    c_b45, &c_b46);
/* 480:[realpole] Real Pole */
/*  Real_Pole */
#line 376 "Main.f"
    rt_33__ = realpole_(&c__0, &c__1, &c__0, &c_b42, &c_b43, &rt_32__, &c_b7, 
	    &c_b45, &c_b46);
/* 490:[pgb] Output Channel 'T =3' */
#line 380 "Main.f"
    s4_1.pgb[ipgb + 14] = rt_33__;
/* 500:[realpole] Real Pole */
/*  Real_Pole */
#line 384 "Main.f"
    rt_34__ = realpole_(&c__0, &c__1, &c__0, &c_b6, &c_b142, &rt_36__, &c_b7, 
	    &c_b45, &c_b46);
/* 510:[realpole] Real Pole */
/*  Real_Pole */
#line 388 "Main.f"
    rt_35__ = realpole_(&c__0, &c__1, &c__0, &c_b42, &c_b43, &rt_34__, &c_b7, 
	    &c_b45, &c_b46);
/* 520:[pgb] Output Channel 'T =6' */
#line 392 "Main.f"
    s4_1.pgb[ipgb + 15] = rt_35__;
/* 530:[realpole] Real Pole */
/*  Real_Pole */
#line 396 "Main.f"
    rt_37__ = realpole_(&c__0, &c__1, &c__0, &c_b6, &c_b158, &rt_36__, &c_b7, 
	    &c_b45, &c_b46);
/* 540:[realpole] Real Pole */
/*  Real_Pole */
#line 400 "Main.f"
    rt_38__ = realpole_(&c__0, &c__1, &c__0, &c_b42, &c_b43, &rt_37__, &c_b7, 
	    &c_b45, &c_b46);
/* 550:[pgb] Output Channel 'T =9' */
#line 404 "Main.f"
    s4_1.pgb[ipgb + 16] = rt_38__;
/* --------------------------------------- */
/* Feedbacks and transfers to storage */
/* --------------------------------------- */
#line 410 "Main.f"
    pscadv3_1.stof[istof] = rt_1__;
#line 411 "Main.f"
    pscadv3_1.stof[istof + 1] = rt_2__;
#line 412 "Main.f"
    pscadv3_1.stof[istof + 2] = rt_3__;
#line 413 "Main.f"
    pscadv3_1.stof[istof + 3] = rt_4__;
#line 414 "Main.f"
    pscadv3_1.stof[istof + 4] = rt_5__;
#line 415 "Main.f"
    pscadv3_1.stof[istof + 5] = rt_6__;
#line 416 "Main.f"
    pscadv3_1.stof[istof + 6] = rt_7__;
#line 417 "Main.f"
    pscadv3_1.stof[istof + 7] = rt_8__;
#line 418 "Main.f"
    pscadv3_1.stof[istof + 8] = rt_9__;
#line 419 "Main.f"
    pscadv3_1.stof[istof + 9] = rt_10__;
#line 420 "Main.f"
    pscadv3_1.stof[istof + 10] = rt_11__;
#line 421 "Main.f"
    pscadv3_1.stof[istof + 11] = rt_12__;
#line 422 "Main.f"
    pscadv3_1.stof[istof + 12] = rt_13__;
#line 423 "Main.f"
    pscadv3_1.stof[istof + 13] = rt_14__;
#line 424 "Main.f"
    pscadv3_1.stof[istof + 14] = rt_15__;
#line 425 "Main.f"
    pscadv3_1.stof[istof + 15] = rt_16__;
#line 426 "Main.f"
    pscadv3_1.stof[istof + 16] = rt_17__;
#line 427 "Main.f"
    pscadv3_1.stof[istof + 17] = rt_18__;
#line 428 "Main.f"
    pscadv3_1.stof[istof + 18] = rt_19__;
#line 429 "Main.f"
    pscadv3_1.stof[istof + 19] = rt_20__;
#line 430 "Main.f"
    pscadv3_1.stof[istof + 20] = rt_21__;
#line 431 "Main.f"
    pscadv3_1.stof[istof + 21] = rt_22__;
#line 432 "Main.f"
    pscadv3_1.stof[istof + 22] = rt_23__;
#line 433 "Main.f"
    pscadv3_1.stof[istof + 23] = rt_24__;
#line 434 "Main.f"
    pscadv3_1.stof[istof + 24] = rt_25__;
#line 435 "Main.f"
    pscadv3_1.stof[istof + 25] = rt_26__;
#line 436 "Main.f"
    pscadv3_1.stof[istof + 26] = rt_27__;
#line 437 "Main.f"
    pscadv3_1.stof[istof + 27] = rt_28__;
#line 438 "Main.f"
    pscadv3_1.stof[istof + 28] = rt_29__;
#line 439 "Main.f"
    pscadv3_1.stof[istof + 29] = rt_30__;
#line 440 "Main.f"
    pscadv3_1.stof[istof + 30] = rt_31__;
#line 441 "Main.f"
    pscadv3_1.stof[istof + 31] = rt_32__;
#line 442 "Main.f"
    pscadv3_1.stof[istof + 32] = rt_33__;
#line 443 "Main.f"
    pscadv3_1.stof[istof + 33] = rt_34__;
#line 444 "Main.f"
    pscadv3_1.stof[istof + 34] = rt_35__;
#line 445 "Main.f"
    pscadv3_1.stof[istof + 35] = rt_36__;
#line 446 "Main.f"
    pscadv3_1.stof[istof + 36] = rt_37__;
#line 447 "Main.f"
    pscadv3_1.stof[istof + 37] = rt_38__;
/* --------------------------------------- */
/* Transfer to Exports */
/* --------------------------------------- */
/* --------------------------------------- */
/* Close Model Data read */
/* --------------------------------------- */
#line 457 "Main.f"
    if (s1_1.timezero) {
#line 457 "Main.f"
	emtdc_closefile__();
#line 457 "Main.f"
    }
#line 458 "Main.f"
    return 0;
} /* dsdyn_ */

/* ======================================================================= */
/* Subroutine */ int dsout_()
{
    /* Builtin functions */
    /* Subroutine */ int s_copy();

    /* Local variables */
    static integer istof, istoi, istol;
    extern /* Subroutine */ int emtdc_openfile__(), emtdc_closefile__(), 
	    emtdc_gotosection__();

/* --------------------------------------- */
/* Standard includes */
/* --------------------------------------- */
/*     -------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING THE SIZE OF THE SYSTEM */
/*     -------------------------------------------------- */
/*     ND1  = MAX. NO. NODES PER SUBSYSTEM */
/*     ND2  = MAX. NO. SUBSYSTEMS */
/*     ND7  = MAX. NO. SUBSYSTEMS IN ALL PAGES */

/*     ---------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING TRANSFORMERS */
/*     ---------------------------------------- */
/*     ND3  = MAX. NO. MUTUALLY COUPLED WINDINGS, */
/*     ND4  = MAX. NO. TRANSFORMERS */

/*     ---------------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING DISTRIBUTED TRANSMISSION LINES */
/*     ---------------------------------------------------------- */
/*     ND5  = MAX. NO. OF MODES OR PHASES */
/*     ND6  = MAX. NO. OF LINES */
/*     ND8  = MAX. NO. OF POLES FOR FREQDEP MODEL */

/*     ---------------------------------------------------------- */
/*     PARAMETERS FOR DIMENSIONING UMEC TRANSFORMER */
/*     (CURRENTLY UNUSED) */
/*     ---------------------------------------------------------- */

/*     -------------------------------------------- */
/*     PARAMETER FOR COMMON BLOCK S2 ( STOR(), NEXC */
/*     -------------------------------------------- */
/*     ND10  = MAX. NO. STOR LOCATIONS */

/*     -------------------------------------------------- */
/*     PARAMETERS FOR COMMON BLOCK S4 ( VAR(),CON(),PGB() */
/*     -------------------------------------------------- */
/*     ND11  = MAX. NO. VAR'S */
/*     ND12  = MAX. NO. CON'S */
/*     ND13  = MAX. NO. PGB'S */

/*     ----------------------------------------------------------- */
/*     PARAMETERS FOR THE MAXIMUM NUMBER OF BRANCHES PER SUBSYSTEM */
/*     ----------------------------------------------------------- */
/*     ND14  = MAX. NO. OF POSITIVE NUMBERED BRANCHES (obsolete) */
/*     ND15  = MAX. NO. OF NUMBERED BRANCHES */
/*     ND16  = MAX. NO. OF THEVININ SOURCES (obsolete) */

/*     ------------------------------------------------------------- */
/*     PARAMETERS FOR THE MAXIMUM NUMBER OF INTERPOLATING SWITCHINGS */
/*     PER SUBSYSTEM */
/*     ------------------------------------------------------------- */
/*     ND17  = MAX. NO. OF ALLOWABLE SWITCHING SUBROUTINES USING */
/*             INTERPOLATION PER SUBSYSTEM (Obsolete) */

/*     ------------------------------------------------------------- */
/*     PARAMETER FOR THE MAXIMUM NUMBER OF B6P110 VALVE GROUP MODELS */
/*     ------------------------------------------------------------- */
/*     ND18  = MAX. NO. OF B6P110 VALVE GROUP MODELS */

/*     ------------------------------------------------------------- */
/*     PARAMETER FOR THE MAXIMUM NUMBER OF ELEMENTS IN THE LOWER */
/*     TRIANGULARIZED CONDUCTANCE MATRIX PER SUBSYSTEM */

/*     A FULL MATRIX WOULD HAVE A MAXIMUM OF ( N*N - N ) / 2 ELEMENTS */
/*     WHERE N IS THE NUMBER OF NODES IN THE SUBSYSTEM */
/*     ------------------------------------------------------------- */
/*     ND19  = MAX. NO. OF SPARSITY ENTRIES PER SUBSYSTEM */

/* Node Map */
/* Pages */
/* NSTOL */
/* NSTOI */
/* NSTOF */
/* NSTOC */
/* NSTORL */
/* NSTORI */
/* NSTORF */
/* NSTORC */
/* TOTAL # OF TRAVELLING WAVE BUFFERS */
/* TOTAL # OF TERMS OF CONSTANT TRANSFORM */
/* TOTAL # OF POLES FOR TRANSFORM */
/* TOTAL # OF POLES FOR ATTENUATION */
/* TOTAL # OF POLES FOR SURGE IMPEDANCE */
/* TOTAL # OF MODES FOR BERGERON/FRE-DEP MOD */
/* TOTAL # OF WIRELESS RADIO TRANSMITTERS */
/* TOTAL # OF WIRELESS RADIO TRANSMITTERS & */
/* TOTAL # OF SPARSE ENTRIES IN 'DU' (HAMONI */
/* Phase Domain Model Dimensions */
/* TOTAL # OF NODES */
/* MAXIMUM NUMBER OF PHASE DOMAIN TLINES */
/* TOTAL   # OF MODES (PHASE DOMAIN) */
/* MAXIMUM # OF MODES (PHASE DOMAIN) */
/* TOTAL   # OF TRAVELLING WAVE BUFFERS (PHA */
/* TOTAL   # OF PROPAGATION BUFFERS (PHASE D */
/* TOTAL   # OF HSERC ELEMENTS (PHASE DOMAIN */
/* TOTAL   # OF YCSERC ELEMENTS (PHASE DOMAI */
/* TOTAL   # OF XHK ELEMENTS (PHASE DOMAIN) */
/* MAXIMUM NUMBER OF POLE/ZEROES (PHASE DOMA */
/* COMMON BLOCK */
/* Spare */
/* ====================================================================== */
/* EMTDC Constants */
/* ====================================================================== */
/* *** */
/* * Values of PI, its fractions and multiples */
/* *** */
/* *** */
/* * Sqare roots */
/* *** */
/* *** */
/* * 1/3 and 2/3 */
/* *** */
/* Type conversion routines */
/* ====================================================================== */
/* ====================================================================== */
/* Common block variables for EMTDC model data STORage */
/* ====================================================================== */
/* STORage Array index usage counters */
/* STORage Arrays (Temporary sizes) */
/* storage: STORx */
/* Logical */
/* Integer */
/* Real */
/* Common Block for EMTDC model data storage */
/* Complex */
/*     CDCTRO = Total winding current including saturation current */
/* TIME    : current time of simulation in seconds */
/* DELT    : simulation time step in seconds */
/* ICH     : Obsolete */
/* PRINT   : print step interval in seconds */
/* FINTIM  : simulation finish tim ein seconds */
/* TIMEZERO: true when time is zero */
/* FIRSTSTEP: true for first step starting from data file or snap file */
/* LASTSTEP: true for last step of the run */
/* ONSTEP:   true if calling from dsdyn/dsout */
/* Data storage array for backward compatibility */
/* Real data storage ( from V3.0 version ) */
/* Running index of STOR array */
/* ======================================================================= */
/* Branch Types (Constants) */
/* ======================================================================= */
/* Breakers */
/* Power Electronic Switches (PESWITCH type) */
/* SWINT5 Breaker */
/* Diode */
/* Thyistor */
/* GTO */
/* IGBT */
/* MOSFET */
/* Arrestors */
/* Transistor */
/* Voltage Sources */
/* Gapless Metal Oxide Arrestor */
/* Current Sources */
/* Branch voltage source */
/* Single phase current source */
/* ======================================================================= */
/* Common Blocks */
/* ======================================================================= */
/* Three phase current source */
/* Branch current */
/* Equivalent history current */
/* Equivalent history current from step */
/* Internal voltage magnitude */
/* EBR from previous time step */
/* ON state resistance */
/* OFF state resistance */
/* Switching level (I,V,or time) */
/* Equivalent conductance */
/* Equivalent ON state conductance */
/* Equivalent OFF state conductance */
/* Equivalent conductance from last step */
/* Factor used in collapsing RLC branch */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/*             " */
/* Total # of switched in SS */
/* Branch # ( switch => branch ) */
/* From node of branch +ve curr. flows o */
/* To node of branch, +ve curr. flows in */
/* Starting location of data storage */
/* True if has resistance */
/* True if has inductance */
/* True if has capacitance */
/* True if has internal source */
/* True if switchable */
/* True if zero impedance (ideal) */
/* True if switch is open (high R) */
/* True if attributes undecided */
/* Flag if an ideal branch is collapsed */
/* True if branch switched w/o interp */
/* =============================================================================== */
/* Common block variables */
/* =============================================================================== */
/* Array index usage counters */
/* Storage: STOx */
/* Control, Monitor */
/* Node, Transformer */
/* Subsystems */
/* DSDYN <-> DSOUT tran */
/* Storage Arrays */
/* Branch */
/* Temporary sizes */
/* Operational Mode */
/* true: Socket exists */
/* Common Block for PSCAD V3 linkage */
/*  NAMES OF ALL INPUT / OUTPUT FILES */
/*  INAM  =  INPUT FILE NAME ( SNAPSHOT OR DATA FILES ) */
/*  TNAM  =  TABLE FILE NAME ( Nodes Table file ) */
/*  INAM1 =  INPUT INCLUDE FILE NAME */
/*  FILENAME =  DATA FILE NAME */
/*  MAPNAME  = Name of the map to be read for this page */
/*  IUNIT =  CURRENT INPUT FILE UNIT NUMBER */
/*  IUNITOUT = STARTING UNIT # FOR OUTPUT FILES */
/*  ONAM  =  OUTPUT FILE NAME ( PGB INFORMATION AND/OR PRINT PLOTS ) */
/*  SNAM  =  END OF RUN SNAPSHOT FILE NAME */
/*           SNAM IF ONLY 1 SNAP TO BE WRITTEN OR MULTIPLE TO SAME FILE */
/*           SNAP-01,SNAP-02 ...  IF INCREMENTAL SNAP TO DIFFERENT FILE */
/*  RTSNAM = Same as SNAM but for runtime snapshot files */
/*  MNAM  =  MULTIPLE RUN FILE NAME */
/*  DUMLIN=  ARRAY USED FOR STORING CURRENT DATA LINE READ */
/*  SECTION= Name of the section last read */
/*  DATALINE = True if nodes from map file are to be read */
/* true while reading network data */
/* --------------------------------------- */
/* Function/Subroutine Declarations */
/* --------------------------------------- */
/* --------------------------------------- */
/* Variable Declarations */
/* --------------------------------------- */
/* Electrical Node Indexes */
/* Control Signals */
/* Internal Variables */
/* Indexing variables */
/* Storage Indexes */
/* --------------------------------------- */
/* Record local indexes */
/* --------------------------------------- */
/* Dsdyn <-> Dsout transfer index storage */
/* SS/Node/Branch/Xfmr */
#line 508 "Main.f"
    ++pscadv3_1.ntxfr;
#line 509 "Main.f"
    istol = pscadv3_1.txfr[pscadv3_1.ntxfr - 1];
#line 510 "Main.f"
    istoi = pscadv3_1.txfr[pscadv3_1.ntxfr + 99];
#line 511 "Main.f"
    istof = pscadv3_1.txfr[pscadv3_1.ntxfr + 199];
/* Record Offset and Increment Storage Counters */
#line 514 "Main.f"
    pscadv3_1.npgb += 17;
#line 515 "Main.f"
    pscadv3_1.nnode += 2;
/* --------------------------------------- */
/* Transfers from storage arrays */
/* --------------------------------------- */
/* --------------------------------------- */
/* Electrical Node Lookup */
/* --------------------------------------- */
/* --------------------------------------- */
/* Read Model data (if any) */
/* --------------------------------------- */
#line 532 "Main.f"
    if (s1_1.timezero) {
#line 533 "Main.f"
	s_copy(fnames_1.filename, "Main.dta", (ftnlen)72, (ftnlen)8);
#line 534 "Main.f"
	emtdc_openfile__();
#line 535 "Main.f"
	s_copy(fnames_1.section, "DATADSO:", (ftnlen)72, (ftnlen)8);
#line 536 "Main.f"
	emtdc_gotosection__();
#line 537 "Main.f"
    }
/* --------------------------------------- */
/* Generated code from module definition */
/* --------------------------------------- */
/* --------------------------------------- */
/* Feedbacks and transfers to storage */
/* --------------------------------------- */
/* --------------------------------------- */
/* Close Model Data read */
/* --------------------------------------- */
#line 553 "Main.f"
    if (s1_1.timezero) {
#line 553 "Main.f"
	emtdc_closefile__();
#line 553 "Main.f"
    }
#line 554 "Main.f"
    return 0;
} /* dsout_ */

